### ISSUE TITLE
Make fails: "cannot find -lnfd"

### ISSUE THREAD

**Issue by Aides359** [kosua20/MIDIVisualizer#1]
Sadly I can currently not get to build your project as the linker cannot find "lnfd" and I cannot find where to get it from.

Please add some installation instructions and required dependencies.

Current steps taken:

```
Clone project
cd projectfolder
make
```

(The requirement to install glfw3 is also only obtainable from reading the comments in the makefile)

**Comment by kosua20** [comment]
Hello,
thank you for your feedback!
I have updated the readme with additional informations for compilation. Note that I haven't tested the Linux version since v1.0, even if I have "mechanically" updated the makefile.

**Comment by kosua20** [comment]
Glad that it finally worked!

The location where glfw and other dependencies are installed will depend on your distribution and/or package manager configuration. I think the link against gtk+ is required by nativefiledialog.
