### ISSUE TITLE
Individual Note Colors

### ISSUE THREAD

**Issue by CDAfonso** [kosua20/MIDIVisualizer#100]
First of all, congratulations for this great project!
It's really good.

It's possible to costumize individual note colors?

Red for C, Green for D , etc..

Thank you

**Comment by CDAfonso** [comment]
I saw your implementing that feature. Awesome! 
Is there any build? I compiled the last version, but didn't figured out if it's working.

Thank you

**Comment by kosua20** [comment]
Hello, I'm glad to hear that you were able to find how it works. If anybody else comes here wondering: in the "Notes" section, you can enable "Per-set colors" and then click the "Define the sets..." button and select the "Key" mode.
I'll generate a new version shortly.

**Comment by kosua20** [comment]
The latest version [has been released](https://github.com/kosua20/MIDIVisualizer/releases/latest)!

**Comment by CDAfonso** [comment]
> The latest version [has been released](https://github.com/kosua20/MIDIVisualizer/releases/latest)!

Thank you, my friend. God bless you!

**Comment by johnmatthewtennant** [comment]
Hi, thank you so much for this feature! I'm trying to assign one colour per note. Right now it seems like it is not possible to assign C and C# to different colours. Is that intended? When I update set 0 under the NOTES dropdown, it also updates set 0 under the MINORS drop down
