### ISSUE TITLE
Add (configurable) alpha for notes

### ISSUE THREAD

**Issue by csillag** [kosua20/MIDIVisualizer#102]
It would be great if we could add alpha to the notes.

Ideally, it should be possible to configure the alpha as a function of the current position of the note (as it is "falling" down), so that it's possible to set it up in such a way that it's almost totally transparent near the top, and then it gradually solidifies as it approaches the bottom.

Here is an example of the desired effect:

https://vimeo.com/554850681/f4e27866b0

To generate this example, I have applied the desired alpha to the output of MIDIVisualizer at a later stage of the processing, which makes my process vveeeeeeeerrrrrryyyyyyy ssssslllllllooooooowww. It would be much faster to add the alpha in MIDIVisualizer, because I had to calculate it for every single pixel, while MIDIVisualizer should only have to do it once per note...

Thanks.

**Comment by kosua20** [comment]
Hello! Sorry for the very late notice, but this was added in v6.5 (a year ago, time flies)!
