### ISSUE TITLE
Key light issue

### ISSUE THREAD

**Issue by nBalykin** [kosua20/MIDIVisualizer#105]
**Describe the issue**
key vusialization does not work correctly on Linux. 
when you press a note before, the whole cluster of notes is highlighted. other notes (D, E, C sharp, etc.) are not highlighted at all.

**Hardware info:**
- OS: **Linux (Manjaro) with latest update**
- MIDIVisualizer version: **6.4**
- GPU model: **AMD Radeon HD8650G (open source driver for linux)**
- RAM available: **I have 12gb in system. available 7-8gb)**

https://user-images.githubusercontent.com/42620164/135090862-75f79518-c8f2-4ad2-9805-42869992ec36.mp4

**Comment by kosua20** [comment]
This has been fixed thanks to Fabien in the latest [v7.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) !
