### ISSUE TITLE
No sound, is this supposed to happen or is it a bug? Please let me know ASAP.

### ISSUE THREAD

**Issue by vanillacometdreamer** [kosua20/MIDIVisualizer#106]
**Describe the issue**
I noticed that no sound is played when I start the MIDI file... is this a bug? 

**Hardware info:**
- OS: 64-bit, Windows 10 Home Edition ver. 20H2
- MIDIVisualizer version: 6.4
- GPU model: I know it's an Intel GPU of some sort, but not the specific model
- RAM: 1 TB
- Computer model: Lenovo IdeaPad 3 15IIL05

**Comment by kosua20** [comment]
Hello, thank you for your interest in MIDIVisualizer! As pointed out by @IamMusavaRibica MIDIVisualizer is currently unable to playback audio. This might be added in a future update, but I can't promise anything short-term 🙂
