### ISSUE TITLE
Separate colors for notes and effects

### ISSUE THREAD

**Issue by sheepkill15** [kosua20/MIDIVisualizer#11]
Hi! I really love this program and used it too, but I couldn't set separated colors for notes and the particles.
I wanna do this because if the blackground is black and I want a darker note color, the particles will be dark too and it's hard to see.

**Comment by kosua20** [comment]
Hello! Thank you for using MIDIVisualizer.
If I'm not mistaken you can already do this: in the control panel there are two color pickers, one for the notes and one for the particles ("Effects"). But I've just realized that by default, the "Lock colors" checkbox is "On", meaning that both colors will be kept in sync when you modify one of them. If you uncheck this, you should be able to define two colors, as shown on the image attached.
I hope this helps! Let me know if you were thinking of any other issue.

![2019-01-10 13_40_22-midi visualizer](https://user-images.githubusercontent.com/3199516/50969236-19d20400-14de-11e9-9829-a7aae7e44fa7.png)

**Comment by sheepkill15** [comment]
Thanks for the fast response. I didn't notice the checkbox, unchecking it fixed my issue. Have a great day!
