### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by theLucy** [kosua20/MIDIVisualizer#111]
I am using this software in OBs picking it up as a game source, it hooks fine and all, but if I use enable transparency in OBS it doesn't remove the background of Midi Visualizer. There are apps that take advantage of this like VSeeFace. This would help to get perfectly clear background without using Chroma Keying. Chroma keying takes time to configure and even then it leaves not perfect result. I don't know if obs support transparency with alpha this way but if it does it would be an amazing addition to this app.

**Comment by sreich** [comment]
To confirm, is there even a transparency...did you disable the background layer/opacity?

If so, maybe it's just a matter of us specifying the framebuffer. If not, I'm not sure how to enable this. Is there OBS documentation for client apps to implement? I haven't used it

**Comment by kosua20** [comment]
Hello, sorry for the late answer! The latest [v7.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) now supports running in a transparent window. This can be enabled in the display options and should hopefully allow you to overlay MIDIVisualizer more easily in OBS.
