### ISSUE TITLE
Export to MIDI

### ISSUE THREAD

**Issue by Alejandro-Stolz** [kosua20/MIDIVisualizer#112]
Would it be possible to export what I played in a keyboard to MIDI, instead of video, in order to import it later or to edit the midi before creating the final video. I think this is currently not possible and it would be a great feature.

**Comment by kosua20** [comment]
Hello, I can this how this can be useful for live sessions, thank you for the suggestion! The latest [v7.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) now supports exporting a recorded session as a MIDI file. It should preserve all the data sent by the peripheral you're using.

**Comment by Alejandro-Stolz** [comment]
Thank you so much!
