### ISSUE TITLE
Particle images are not loaded, and colors for notes/particles are always synced.

### ISSUE THREAD

**Issue by Nesrality** [kosua20/MIDIVisualizer#116]
Hi, and thank you very much for making this great visualizer.. I really love it... But, there is something that does not work as described.  It says I can load up to 4 particle image, and I did it with the one I downloaded from here, (the musical notes and symbols) but only one shows up... I also would love to have different color in the notes and the particles, but if I change the particle colors, the notes will get the same color. Anything I overlook here?

**Comment by cronozius** [comment]
Bonjour, oui moi aussi j'ai le même soucis, je veux mettre des couleurs différentes pour pouvoir mettre les touches noires plus foncées que les blanches.. Cependant dès que je change une couleur, la précédente change aussi, donc on ne peut mettre que une seule couleur, si vous pouviez régler ce problème c'est serait génial merci 🦋🤠

**Comment by kosua20** [comment]
Hello I'll investigate the issue regarding the particle images not loading.
Regarding the fact that notes (major and minor) and particles are stuck with the same color, make sure to uncheck "Sync effect colors" to be able to customize each color. Hopefully this should fix the issue.

**Comment by kosua20** [comment]
The latest [v7.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) should clarify that it's possible to have multiple color sets and disable the default "all colors are synchronized" mode (which can still be enabled through the checkbox). It's also now possible to assign notes to color sets with more control (see the "Define sets... > List" mode).

For loading the particle files, I haven't been able to reproduce this issue. Did you select the four pictures at the same time in the file picker? I'll try to think of an interface to make the process easier (and maybe allow more than four pictures if possible 🙂)

**Comment by cronozius** [comment]
Thanks you 🌹 i will upload the last Version 7 🥰

Le mar. 13 déc. 2022 à 20:17, Simon Rodriguez ***@***.***> a
écrit :
