### ISSUE TITLE
Configuration doesn't load automatically upon relaunch

### ISSUE THREAD

**Issue by lcalder** [kosua20/MIDIVisualizer#119]
Steps to produce:

1. Launch MIDIVisualizer
2. make a bunch of changes
3. save those changes to a file
4. exit app and relaunch
5. must manually load configuration every time

**Hardware info:**
ardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	64 GB
  System Firmware Version:	7459.121.3
  OS Loader Version:	7459.121.3
  Serial Number (system):	QYY0PY654K
  Hardware UUID:	A9329206-2B36-5E85-9D3B-9DBFE8B1F30B
  Provisioning UDID:	00006001-001268100A9A801E
  Activation Lock Status:	Disabled

This is an amazing piece of software.  If you have a patreon or other way to donate I will happily do so.
Thanks

Please don't forget that MIDIVisualizer is a personal project that I maintain on my free time, free to use and open source :)

**Comment by kosua20** [comment]
As mentioned in #120 the latest version now supports this feature 🙂
