### ISSUE TITLE
Other features I think this visualizer would benefit from

### ISSUE THREAD

**Issue by MadLad0913** [kosua20/MIDIVisualizer#12]
Hello, it's me again! I thought of more additions for this visualizer, such as the ability to change the color of the horizontal/vertical lines. This can help increase contrast against backgrounds (like bright red) or darken lines for a more subtle effect. Another feature that I thought of was the ability to change the color of the sharp and flat notes. The ability to choose a different color for these notes should give the visualizer more color variety. The last feature that I would want is the ability to replace the flashes with other images (like the particles) for more aesthetic. The ability to change the size and color of the flashes would be great too. Thank you for this awesome visualizer, keep up the great work!

**Comment by kosua20** [comment]
Hello, most of your suggestions are now implemented and will be available in the 3.3 release.
The flash texture is a tricky one, because it is an animate sprite (you can see the 'texture atlas' containing the frames in the `ressources` directory), but I'll consider it!

**Comment by MadLad0913** [comment]
Thank you, can't wait to test them out!

**Comment by kosua20** [comment]
Version 3.3 has just been released!

**Comment by kosua20** [comment]
Hello, I'm resurrecting this thread to let you know that the flash image atlas can be customized in the latest [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest). Better (very) late than never 😄
