### ISSUE TITLE
Upon loading configuration file, Display settings and Midi Input Device settings aren't saved

### ISSUE THREAD

**Issue by lcalder** [kosua20/MIDIVisualizer#120]
Steps to produce:

1. Launch MIDIVisualizer
2. make a bunch of changes including changes to Display (1920x1080) and Midi device selection
3. save those changes to a file
4. exit app and relaunch
5. manually Load saved configuration.
6. Must reinput Display settings and Midi Device selection on every launch

**Hardware info:**
ardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	64 GB
  System Firmware Version:	7459.121.3
  OS Loader Version:	7459.121.3
  Serial Number (system):	QYY0PY654K
  Hardware UUID:	A9329206-2B36-5E85-9D3B-9DBFE8B1F30B
  Provisioning UDID:	00006001-001268100A9A801E
  Activation Lock Status:	Disabled

This is an amazing piece of software.  If you have a patreon or other way to donate I will happily do so.
Thanks

Please don't forget that MIDIVisualizer is a personal project that I maintain on my free time, free to use and open source :)

**Comment by kosua20** [comment]
Hello, and thank you for the feedback! This was until now not supported by MIDIVisualizer (the config only saves theme parameters). But the latest [v7.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) can now restore its settings at launch, including the display settings.
