### ISSUE TITLE
FindFFMPEG.cmake couldn't find ffmpeg on windows at all

### ISSUE THREAD

**Issue by BluestarCo** [kosua20/MIDIVisualizer#121]
Hi
i can't use ffmpeg in project

Could NOT find FFMPEG (missing: FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIRS AVCODEC_LIBRARIES AVCODEC_INCLUDE_DIRS AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS) 

![Capture](https://user-images.githubusercontent.com/6850093/178063684-d600706f-b43e-4c10-be7d-0a6ce0f52060.PNG)

please give me some instruction to config ffmpeg path in right way

**Comment by kosua20** [comment]
Hello, the simplest way to compile with ffmpeg enabled is to download the compiled FFMPEG dependency from https://github.com/kosua20/MIDIVisualizer-dependencies/releases/tag/v1 For Windows you'll want the file `ffmpeg-windows-64-static-lgpl.zip`.
Unzip its content in the `MIDIVisualizer/libs` directory, and copy `libs/ffmpeg/share/ffmpeg/FindFFMPEG.cmake` to `libs/` (you will have to overwrite the existing file). Afterwards, re-configure/generate in Cmake and FFMPEG should be detected properly.
