### ISSUE TITLE
Improve and/or add various piano note flashes (note start point)

### ISSUE THREAD

**Issue by sreich** [kosua20/MIDIVisualizer#124]
Add some additional prettier effects, or an improved one, to the piano note flash. Just from glancing without the code yet, looks texture map based, it isn't very smoothly transitioned (part of this is the velocity which is another github issue here). But most of it is the look and feel of it can be made to look more natural and less...cartoony

A good model to follow is the ones from Ember, https://www.youtube.com/watch?v=KgGZ5yX96T4 and such. atinpiano has some good effects overall to mirror those would be really awesome.

**Comment by kosua20** [comment]
Hello, I've added the ability to customize the image flipbook used to animate the flash, along with some additional halo settings. This is available in the latest [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) and should give you more flexibility in customizing the flashes appearance.

**Comment by sreich** [comment]
Awesome! I'll check it out, thank you
