### ISSUE TITLE
Can't compile with latest libavcodec versions

### ISSUE THREAD

**Issue by csillag** [kosua20/MIDIVisualizer#125]
Compiling with libavcodec-dev 5.1.2 fails with this message:

```
src/helpers/Recorder.cpp:402:31: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  402 |  _codec = avcodec_find_encoder(outFormat.avid);
      |           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
      |                               |
      |                               const AVCodec*

```

On the same system, compilation works fine after downgrading libavcodec (and assorted packages) to 4.3.x

It would be nice if it could be updated to be compatible with latest ffmpeg.

**Comment by kosua20** [comment]
This has been fixed thanks to a merged pull request (#118) (bbf9d46e303bbe82aedaa7b95993b2a079d0f28b). I'll try to update the FFMPEG version used in the release pipeline soon.
