### ISSUE TITLE
Config file is not loaded [linux bug]

### ISSUE THREAD

**Issue by Alejandro-Stolz** [kosua20/MIDIVisualizer#133]
On linux the config file is not loaded correctly when selected from the file selector window. I don't know yet why, but linux or maybe the file manager nautilus has a problem uploading files to certain programs. In firefox I can't upload images. When I try to load a config file from the GUI, the window does not load any settings and the GUI looks like this:
![image](https://user-images.githubusercontent.com/73649874/215286480-b09b74c1-cc11-44cb-b94a-5d9015c40a59.png)
It also displays the following message on the console:
[CONFIG]: Ignoring key sets-separator-control-points: without arguments.

This is not a problem of the software because if I pass the --config argument at startup all the settings are loaded correctly, it is just information for anyone who encounters the same "bug" and looks for help.

**Hardware info:**
- OS: LINUX / Ubuntu 22
- MIDIVisualizer version 7.0

**Comment by kosua20** [comment]
Hello, thank you for your feedback and for posting this to help others! I'll still try to investigate if I can reproduce the issue on Ubuntu 22 and Nautilus, to at least detect the problem and warn the user. If you still have one of the config files around, could you share it with me? maybe Nautilus is not expecting something in the file name or the path.

**Comment by Alejandro-Stolz** [comment]
Thank you very much!!!!
