### ISSUE TITLE
audio either missing, or not supported

### ISSUE THREAD

**Issue by ApianbelleDev** [kosua20/MIDIVisualizer#134]
upon opening, there's not audio. is there supposed to be? I understand this is a midi visualizer, but I'd assume it'd have audio too. if not, when will audio be added? as far as I've seen, this is the only app like this that runs almost perfectly on linux distros, so I'd like for this to at least be *usable*.

**Comment by Alejandro-Stolz** [comment]
![image](https://user-images.githubusercontent.com/73649874/216042299-c04f7016-af72-4f31-b06d-cbcd3222216a.png)
It is a midi visualizer only. It be pretty neat if it could generate audio from the midi or a load a custom mp3. Anyways, it would need to be a FR(Feature Request) and not a bug.

**Comment by asl97** [comment]
there was only 17 open issue, one of them being #61 

assuming I ain't reading it wrong, kind of wish they added midi out as part of #39/#83 which would simplify things and allow normal playback with audio.

Right now you could do reverse scrolling playback with audio by using amidiplay or other software/devices and simply connect to both midivisualizer and a synth, maybe add delay via amidi to sync both software

**Comment by ApianbelleDev** [comment]
> It is a midi visualizer only.

I must've completely missed that. apologies
