### ISSUE TITLE
Sound doesn't work?

### ISSUE THREAD

**Issue by BeeManGames** [kosua20/MIDIVisualizer#141]
So I just download this and I opened it and started playing around with it. But there was no sound. I have the windows 64-bit download btw.

**Comment by kosua20** [comment]
Hello, currently MIDIVisualizer is only a viewer and does not provide audio playback functionality, sorry! I know this is a popular request ; it might be added at some point in the future, but I have no ETA for it at the moment.
Thanks for your feedback!

**Comment by jalopez81** [comment]
What the.... why on earth would one want a visualizer with no sound??
