### ISSUE TITLE
Add an option to hide GM drums channel (channel 9)

### ISSUE THREAD

**Issue by 3119369616** [kosua20/MIDIVisualizer#143]
General MIDI channels are 0~15 and channel 9 is for drums. Is it possible to add an option to hide it?

**Comment by kosua20** [comment]
Hello, thank you for your feedback! I think having the option to hide some channels or some tracks would be interesting indeed. I'll add it to the list of future features.

**Comment by kosua20** [comment]
Hello, I've added options to show/hide any channel or track in the latest [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) !
