### ISSUE TITLE
Any chance of a Macos ARM version?

### ISSUE THREAD

**Issue by lcalder** [kosua20/MIDIVisualizer#145]
This program is wonderful. I do see a bit of a performance hit when it is running. I wonder how much more efficiently it would run if there were a native ARM version...

**Comment by kosua20** [comment]
Hello! That's a good suggestion, I've done some tests to generate a universal binary for macOS with native support for both x64 and ARM versions. If you want to test it, you can find the resulting build in this side-repository: https://github.com/kosua20/MIDIVisualizer-CI-tests/releases/tag/test19  (sorry for the obscure names, this is where I usually test the automated build system to avoid messing up the main repository). 
As I don't have an ARM mac at hand, I have no guarantee that it will runs properly (but you should always be able to force Rosetta emulation in the .app properties).

**Comment by lcalder** [comment]
Wow! Thanks. I will test it and let you know.

**Comment by lcalder** [comment]
I tested on my M2 Pro and so far it is working fine.

**Comment by kosua20** [comment]
Great, thank you for testing! I'll enable this for future releases.

**Comment by lcalder** [comment]
Thanks!
