### ISSUE TITLE
Notes should not overlap particles

### ISSUE THREAD

**Issue by tastyForReal** [kosua20/MIDIVisualizer#147]
I'm not sure if this is intended, but they feel kind of bad with different colors.

[Here's my INI Configuration if you want to take a look.](https://github.com/kosua20/MIDIVisualizer/files/12543633/Riria.-.Anata.no.Soba.ni.MIDIVisualizer.ini.txt)

![Screenshot 2023-09-07 090745](https://github.com/kosua20/MIDIVisualizer/assets/40455776/85f621a8-c7d6-4552-a8f2-f4f8e6c95041)

As with other piano visualizers (i.e., Embers), this seems to look more correct.

![Porter Robinson - Blossom (LyricWulf Piano Cover) 0-18 screenshot](https://github.com/kosua20/MIDIVisualizer/assets/40455776/39cde601-47f4-495b-a166-7f09ac147fc7)

**Comment by tastyForReal** [comment]
I believe there should be a toggle to turn off notes overlapping particles. In my case, I'm adding pink flower particles using an image, but the results are so bad that I've resorted to not using the particles layer at all.

**Comment by tastyForReal** [comment]
There's going be a toggle to turn off notes overlapping particles as shown in this image, right?

![result3](https://github.com/kosua20/MIDIVisualizer/assets/40455776/d82933cc-7899-49fe-8b55-7bbd1d859493)

**Comment by kosua20** [comment]
Hello, the option for reordering effects on top of each other is a bit hidden. You have to click the "Show effect layers..." button, and in the panel that opens, you will be able to drag and drop items in the list to decide which effect is rendered on top of which. 
Let me know if this helps!

**Comment by tastyForReal** [comment]
Yeah, I was definitely missing out, or it's a little too subtle from my UX (User Experience) perspective, but, thanks for your help!

**Comment by kosua20** [comment]
I agree that the discoverability for some of the options is suboptimal right, this is something I need to address at some point!
