### ISSUE TITLE
Midi files get stuck

### ISSUE THREAD

**Issue by wesleykendall** [kosua20/MIDIVisualizer#16]
I've tried loading 4 different midi files on a Macbook Air with Mojave. The visualization works great up to a point, but then notes become "stuck" or simply stop appearing.

![Screen Shot 2019-04-07 at 5 05 33 PM](https://user-images.githubusercontent.com/1497710/55691868-67cc9b80-5957-11e9-982e-11709f3c4186.png)

I verified this same behavior on the pre-compiled version all the way to 2.1, and I've also compiled it myself to come across the same behavior.

The midi for the above screen shot is at https://drive.google.com/open?id=1Er6lBhaKwV_liCMiDdjTvKAvIxUEAB06

It also doesn't get past the first two notes of this midi https://drive.google.com/open?id=1lAexUmJ2J93oEyaUIvO-FujWqKsS3N9o

I verified that these two midis could be visualized with http://qiao.github.io/euphony/#20 just fine.

Any idea what might be going on? I love this tool!

**Comment by wesleykendall** [comment]
I had my friend try out the exact same midi file on a 64-bit windows machine today too. He experienced the same result, seeing only the first two notes followed by nothing else. I originally thought it might be Mac related, but it seems that my midi files might be causing the issues. If you have any ideas of how I could fix it, I'd really love to use this software. It's so great! I've done OpenGL / C++ stuff quite a bit as well if you can point me in the right direction of where to look

**Comment by kosua20** [comment]
Hello! Thank you for reporting this issue, I'll look into it. I think it might be related to the MIDI file parsing rather than the rendering, as MIDIVisualizer currently only support some "types" of MIDI. I'll keep you up to date.

**Comment by wesleykendall** [comment]
@kosua20 thanks so much! I was thinking it might be the same thing. These midi files are recorded directly from an instrument for reference. I tried converting them to different midi types and other things but didn't have much luck. I've been meaning to take a look at the code

**Comment by kosua20** [comment]
I think I have found the issue: the instrument generated a lot of `changedPressure` and `unknown` MIDI events (probably some custom events defined by the manufacturer) with extremely long durations, which should probably be ignored when computing the track timings. 
I've pushed code modifications to prevent this, let me know if the timings are ok now.

**Comment by wesleykendall** [comment]
That did the trick! Thanks!
