### ISSUE TITLE
Support delay before the play

### ISSUE THREAD

**Issue by dzikoysk** [kosua20/MIDIVisualizer#18]
It could be great to specify the number of seconds before the start of midi visualization. At this moment we need to add this gap to the midi file to avoid beginnings like that: (notes that start at 0:00)

![obraz](https://user-images.githubusercontent.com/4235722/56694888-160e6a00-66e8-11e9-9067-2b2c1ea946a7.png)

It might be useful for video creators etc.

**Comment by kosua20** [comment]
Hello, that's a very good suggestion, I'll add it to the next release and will keep you up to date!

**Comment by kosua20** [comment]
MIDIVisualizer 3.4 has now been released ! (https://github.com/kosua20/MIDIVisualizer/releases)
For now the shift is constant (1 second) but that could be exposed in the user interface if needed.

**Comment by dzikoysk** [comment]
I think it could be useful to be able to set the shift in the interface. In most cases when someone is recording the visualizer with a real piano, it takes a few seconds to start. I also think it should be the float value instead of int, not a big deal but might be helpful.

**Comment by kosua20** [comment]
Hello again! MIDIVisualizer 4.0 (https://github.com/kosua20/MIDIVisualizer/releases/tag/v4.0) now supports a custom "preroll" shift, which should be helpful for recording.
