### ISSUE TITLE
Background customization

### ISSUE THREAD

**Issue by dzikoysk** [kosua20/MIDIVisualizer#19]
Another feature that you could consider as a next enhancement is extended configuration of background. The possibility of selecting an image as a background could be great. At this moment I'm thinking about:
* background image
* opacity

For instance:

![obraz](https://user-images.githubusercontent.com/4235722/56772788-b84b5200-67bb-11e9-94e4-dbdbc0c5435e.png)

~source: https://www.youtube.com/watch?v=beHDN-2uXLk

**Comment by kosua20** [comment]
That's a very good suggestion, and I've added it in MIDIVisualizer 4.0 (https://github.com/kosua20/MIDIVisualizer/releases/tag/v4.0).
You can set the opacity of the texture, alpha is supported if you load a PNG with transparency, and you can chose if the image should extend below the keyboard.
Thank you!
