### ISSUE TITLE
Help with running on Windows

### ISSUE THREAD

**Issue by damienborowski** [kosua20/MIDIVisualizer#20]
This isn't an issue but i am having issues running this on windows and was hoping for a detailed explanation on how to download and run this?

**Comment by dzikoysk** [comment]
Download the latest version from releases for your platform (32/64bit): https://github.com/kosua20/MIDIVisualizer/releases, then:
> On all platforms, you can now run the application by simply double-clicking on it. You will then be able to select a MIDI file to load.
