### ISSUE TITLE
Vertex shader error

### ISSUE THREAD

**Issue by link2012** [kosua20/MIDIVisualizer#22]
Hi, thanks for amazing app. I really like it.
I found some issue on v3.4

![vertex shader error](https://user-images.githubusercontent.com/50038523/56844572-66a2e480-68ed-11e9-834b-966add540efb.png)

With v3.4, I got this error. Particles are messed up.
In v3.3, I don't have issue like this.

**Comment by kosua20** [comment]
Hello, thank you for this feedback!
I've fixed some particles-related bugs in MIDIVisualizer 4.0 (https://github.com/kosua20/MIDIVisualizer/releases/tag/v4.0), so you might want to give it a try.
Let me know if this helps!
