### ISSUE TITLE
Can I port this to use CMake for building for all platforms?

### ISSUE THREAD

**Issue by NamedKitten** [kosua20/MIDIVisualizer#25]

**Comment by kosua20** [comment]
Hello! Thank you for your suggestion! Porting to Cmake would be welcomed, and would avoid having to maintain two makefiles and a Visual Studio project manually.
Note that I won't be very responsive until the end of May for professional reasons, but I'll still try to check issues and PRs from time to time :)

**Comment by dzikoysk** [comment]
Hey @NamedKitten, are you going to implement this in the near future? :heart:

**Comment by NamedKitten** [comment]
@dzikoysk yeah but i'm doing my GCSEs/finals so I'll be busy >.<

**Comment by dzikoysk** [comment]
Oh, that's fine, good luck with it :)

**Comment by kosua20** [comment]
Hello, I've started to port MIDIVisualizer to Cmake, tested on Windows for now.

**Comment by kosua20** [comment]
And tested on macOS. I don't have a Linux distrib available right now, but the Cmake is pretty simple so that should™ work.
