### ISSUE TITLE
Particle don't work PC window 10

### ISSUE THREAD

**Issue by Labelchamp** [kosua20/MIDIVisualizer#28]
![MIDIVisualizerx64_vn9QBym4T8](https://user-images.githubusercontent.com/50407551/57376412-1c154800-71ca-11e9-9af6-11458273184a.png)
![4RRLkhk909](https://user-images.githubusercontent.com/50407551/57376414-1cadde80-71ca-11e9-97fd-68ba1f8ec2c6.png)
![MIDIVisualizerx64_xqZXXhiJpF](https://user-images.githubusercontent.com/50407551/57376415-1cadde80-71ca-11e9-81eb-4d094a40dd60.png)

i don't know how to explain to you becuase my english skill so bad 

please help me

**Comment by Labelchamp** [comment]
and new question how to export to media 

i click render offline and get  6000+ picture

**Comment by kosua20** [comment]
Thank you for reporting this bug!
Regarding the export, MIDIVisualizer basically export each frame of the video, that you can then merge using video editing tools (Virtualdub, MovieMaker, Premiere,...). For now direct export to video is not supported, sorry about that.

**Comment by kosua20** [comment]
Hello again! Just to let you know that I fixed some particles-related bugs in MIDIVisualizer 4.0 (https://github.com/kosua20/MIDIVisualizer/releases/tag/v4.0). Let me know if it helps!

**Comment by Labelchamp** [comment]
let me try  thank you very much

ในวันที่ จ. 28 ต.ค. 2019 เวลา 13:55 Simon Rodriguez <
notifications@github.com> เขียนว่า:

**Comment by Labelchamp** [comment]
wowwwww  that's work thank you very much

ในวันที่ จ. 28 ต.ค. 2019 เวลา 17:05 Cool Champ <labelchamp@gmail.com>
เขียนว่า:

**Comment by kosua20** [comment]
No problem, I'm glad this is fixed and sorry for the delay.

**Comment by Labelchamp** [comment]
That's ok  you are the best

This make me easily for make my next video thank you so much

ในวันที่ อ. 29 ต.ค. 2019 02:33 น. Simon Rodriguez <notifications@github.com>
เขียนว่า:
