### ISSUE TITLE
Interesting project, seems to be inspired by Synthesia

### ISSUE THREAD

**Issue by michaelsjackson** [kosua20/MIDIVisualizer#29]
Thanks for sharing your code here. Will check it from time to time again, as a Synthesia lover and user. It is always good having multiple options, in this case even with source for learning purposes.

**Comment by kosua20** [comment]
Thank you 😄

**Comment by Bear0White** [comment]
Amazing Work!

**Comment by kosua20** [comment]
Thank you!
