### ISSUE TITLE
Modifying particle/blur velocity?

### ISSUE THREAD

**Issue by turboman1** [kosua20/MIDIVisualizer#3]
Hello,
I am trying to find the function that controls the _velocity_ for the particles+blur.
(I'm new to c++/openGL so I apologize if this question is trivial)
Many thanks!

**Comment by kosua20** [comment]
Hello,
Those parameters are numbers in the `particles` and `particlesblur` shaders. I've renamed them to expose them more clearly.

Particles speed factor: [particles.vert:31](https://github.com/kosua20/MIDIVisualizer/blob/c6db32902efc5e598b0dc70f184557e29da88d03/ressources/shaders/particles.vert#L31)
Blur fading factor: [particlesblur.frag:15](https://github.com/kosua20/MIDIVisualizer/blob/c6db32902efc5e598b0dc70f184557e29da88d03/ressources/shaders/particlesblur.frag#L15).

You will have to `make package` and `make midiviz` to see your updates in the application, as discussed in #2 .
Those parameters could be exposed in the interface and passed through the C++/OpenGL code to the shaders, as uniforms, to enable the user to tweak them while using the executable.
