### ISSUE TITLE
Interval lines from note to note

### ISSUE THREAD

**Issue by michaelsjackson** [kosua20/MIDIVisualizer#30]
See more explanation here: https://github.com/michaelsjackson/reaper_forums/issues/1

**Comment by michaelsjackson** [comment]
Closed, was this implemented already or just closed? Thanks in both cases.

**Comment by kosua20** [comment]
Hello, sorry I'm not planning on implementing this for now... I've recently added channel support so I might look at it in the future but I don't want to promise anything. I kept it listed in the Project tab (https://github.com/kosua20/MIDIVisualizer/projects/1) so that I don't forget about it 😃

**Comment by michaelsjackson** [comment]
Thanks for replying my friend. No problem, if you do not implement it. At least you have one more interesting idea what could be useful, especially for getting an overview of interval structure, no matter if from Beethoven or some dance tune.

**Comment by michaelsjackson** [comment]
Or I might use this as a small c++ c practice project, adding it myself, one day, if it should work, I can share my results back here. Interesting nobody sees any value seeing the interval relationships. At least the musician and composer Paul Nelson saw the usefulness of this concept and implemented even a separate application for this, MusicGraph.    Everyone their own, some want analysis, others game like output.  Having both would be also not bad.  Requested this also for Reaper DAW, but no progress there as well.  Have a nice day.
