### ISSUE TITLE
can't load midi file in win 10

### ISSUE THREAD

**Issue by mohsen8577** [kosua20/MIDIVisualizer#31]
this version not work for me
hang up the program when i want load a midi file
But previous versions work fine

**Comment by kosua20** [comment]
Hello, thanks for reporting this issue! Does the program simply crash? With all MIDI files? Could you send me a file that crash, that would be incredibly helpful.

**Comment by mohsen8577** [comment]
yes with all midi files
i reinstalled win10 But I'm still having trouble

**Comment by kosua20** [comment]
When lauching the application, is there any error message in the "command line" window that pops up, or does it crash/hangs immediatly? Or is it only when loading a midi file? Do you know what is the GPU model in your machine? Thanks!

**Comment by mohsen8577** [comment]
Exits the program when i load a midi file
and when run program with run adminstrator , i have a different error
i will sen error pic
my gpu is intel hd 4000

**Comment by kosua20** [comment]
Thank your for these details! I haven't pinpointed the exact source of the issue yet, but you might want to test the latest version of MIDIVisualizer 4.0 (https://github.com/kosua20/MIDIVisualizer/releases/tag/v4.0) just in case. Let me know if this helps!

**Comment by mohsen8577** [comment]
Hey,

I just signed the petition "Parliament of Canada: Remove Majid Jowhari from
Parliament" and wanted to see if you could help by adding your name.

Our goal is to reach 5,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/g6TRMRkfwb

Thanks!
meysam

**Comment by kosua20** [comment]
I'm going to assume the previous message  was sent by error to the email address associated to this issue. Issues are used for and *only for* reporting and keeping track of technical problems related to the project. Thank you for respecting this!

I'll delete the aforementioned message in a few hours.

**Comment by mohsen8577** [comment]
Hey,

I just signed the petition "Turkish Government: FREE AMIR TATALOO - TURKISH
GOV NOT TO HAND TATALOO TO IRANIAN GOV!" and wanted to see if you could
help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/fSNH6SVXmL

Thanks!
mohsen
