### ISSUE TITLE
Particles start lower than the notes

### ISSUE THREAD

**Issue by Bandicooted** [kosua20/MIDIVisualizer#33]
Hey, congrats on this project.

I've noticed that the particles are not created in the same place where the notes end. 
This results in particles popping up out of sync with the track, specially noticeable for me since I was meaning to use 0.300 expansion.

![image](https://user-images.githubusercontent.com/3803313/58245722-585db200-7d4d-11e9-9a80-5faa57a50f8f.png)

This is especially noticeable if you remove the sparks:

![image](https://user-images.githubusercontent.com/3803313/58245779-79260780-7d4d-11e9-841a-455ab32615d0.png)

Is this something that could be fixed? Or, if for some reason this is exactly how you want it, it wold be nice to have the option to dislocate it in the settings :)

**Comment by kosua20** [comment]
Hello! I've fixed the particles initial position in MIDIVisualizer 4.0 (https://github.com/kosua20/MIDIVisualizer/releases/tag/v4.0).
Thank your for your feedback!
