### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by pistonhunter** [kosua20/MIDIVisualizer#35]
Hey! When i download and double click the exe file, it doesn't start  instead, a command prompt window flashes for a second and disappears. I am using Windows 7 ultimate 32 bit version. And i have tried the 32 bit version of midi visualizer. Please help me. I took a video of the screen and paused it to know what the command prompt says. It says "ERROR Could not open window with GLFW3"
I don't know coding. I am a pianist and i opened a github account just to get this fixed. So kindly help me out. 🙂 I dont know coding. How can i make the exe file work? Anyone please help

**Comment by pistonhunter** [comment]
I took a video of the screen and paused it to know what the command prompt says. It says "ERROR Could not open window with GLFW3"

**Comment by kosua20** [comment]
Hello, sorry to hear that!
Do you know what kind of GPU your computer has? Usually this type of error happens when the GPU driver is outdated. Please also note that I haven't tested MIDI Visualizer on Windows 7 recently ...

**Comment by pistonhunter** [comment]
Thanks a lot for replying. 
I have got the windows 7 installed yesterday. So maybe i havent installed all the drivers. I installed visual c++ redistributables (something like that) which fixed some dll errors in vsdc video editor. But still midi visualizer is not working. I also installed the vga drivers from acer website. I will type in the specs. Please look into it and help me out. 
The laptop I am using is Acer Aspire 1810tz. 
Os: windows 7 Ultimate Service pack 1
Processor: Genuine Intel(R) CPU U4100 @1.30Ghz 1.30GHz
Ram: 2GB
System type: 32bit Operating system

**Comment by kosua20** [comment]
Thank you for those details!
From what I can see online [(Wikipedia)](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen4), the Intel GMA 4500MHD  and its latest driver only supports OpenGL 2.1, while MIDIVisualizer is an OpenGL 3 application. I won't bother you with the details, but OpenGL 3 changed a lot of things in the way the application interacts with the GPU, so the code is quite different and porting it back to OpenGL 2 would require a rewrite...
So I'm afraid there is not easy way to run MIDIVisualizer on your computer, I'm sorry :/

**Comment by pistonhunter** [comment]
Aww 😔 
Thanks for replying.
