### ISSUE TITLE
No longer working under WINE

### ISSUE THREAD

**Issue by glitterball** [kosua20/MIDIVisualizer#37]
Hi,
Many thanks for your excellent work on this project.
I am using the windows 32bit version under WINE on Linux (I can't figure out how to compile a Linux version from source). However, since version 3.3, it no longer works under WINE (v3.2 is the last working version).

The error details are as follows:
Unhandled exception: page fault on execute access to 0x00000000 in 32-bit code (0x00000000).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:006b GS:0063
 EIP:00000000 ESP:0033f408 EBP:0033f468 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000001 EBX:7f4edf38 ECX:404237fd EDX:00000000
 ESI:00000000 EDI:00000000
Stack dump:
0x0033f408:  00473bc0 00010060 00000000 00010060
0x0033f418:  00000000 00010060 0000001b 00000000
0x0033f428:  0033f82c 7f4edf38 7f5d9540 00000300
0x0033f438:  00000000 06c00000 00010060 7dd72c80
0x0033f448:  06c00000 00000014 0033f6bc 0000000f
0x0033f458:  0033f480 00000020 7f4edf38 4071c395
Backtrace:
=>0 0x00000000 (0x0033f468)
  1 0x7f4a7b2c in user32 (+0x97b2b) (0x0033f498)
  2 0x7f4a8239 in user32 (+0x98238) (0x0033f4e8)
  3 0x7f4aa553 in user32 (+0x9a552) (0x0033f538)
  4 0x7f46854e in user32 (+0x5854d) (0x0033f5a8)
  5 0x7f46f2c9 in user32 (+0x5f2c8) (0x0033f608)
  6 0x7f46f537 in user32 (+0x5f536) (0x0033f658)
  7 0x7f49d89c in user32 (+0x8d89b) (0x0033f7e8)
  8 0x7f496f39 in user32 (+0x86f38) (0x0033f878)
  9 0x004795ee EntryPoint+0xffffffff() in midivisualizer (0x0033fa60)
  10 0x00474e33 EntryPoint+0xffffffff() in midivisualizer (0x0033fe88)
  11 0x0047c1e3 EntryPoint+0xffffffff() in midivisualizer (0x0033fed0)
  12 0x7b464a82 in kernel32 (+0x44a81) (0x0033fee8)
  13 0x7b466d5d in kernel32 (+0x46d5c) (0x0033ffd8)
  14 0x7b464a8e in kernel32 (+0x44a8d) (0x0033ffec)
0x00000000: -- no code accessible --
Modules:
Module	Address			Debug info	Name (37 modules)
PE	  400000-  52a000	Export          midivisualizer
PE	7a820000-7a824000	Deferred        opengl32
PE	7b420000-7b5d1000	Export          kernel32
PE	7bc10000-7bc14000	Deferred        ntdll
PE	7da60000-7da64000	Deferred        dwmapi
PE	7da80000-7da84000	Deferred        uxtheme
PE	7dcd0000-7dcd4000	Deferred        xinput1_4
PE	7dcf0000-7dcf4000	Deferred        winex11
PE	7dd80000-7dd83000	Deferred        usp10
PE	7ddd0000-7de4d000	Deferred        comctl32
PE	7df40000-7df4b000	Deferred        dinput8
PE	7df80000-7df89000	Deferred        msacm32
PE	7dfb0000-7e028000	Deferred        winmm
PE	7e080000-7e083000	Deferred        msvcr120
PE	7e160000-7e163000	Deferred        concrt140
PE	7e480000-7e483000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	7e490000-7e493000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	7e4a0000-7e4a3000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	7e4c0000-7e4c3000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	7e4d0000-7e4d3000	Deferred        api-ms-win-crt-math-l1-1-0
PE	7e4f0000-7e4f3000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	7e500000-7e503000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	7e520000-7e523000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	7e530000-7e533000	Deferred        api-ms-win-crt-string-l1-1-0
PE	7e550000-7e553000	Deferred        vcruntime140
PE	7e580000-7e584000	Deferred        ucrtbase
PE	7e6a0000-7e6a3000	Deferred        msvcp140
PE	7e790000-7e794000	Deferred        imm32
PE	7e7c0000-7e7c4000	Deferred        rpcrt4
PE	7e850000-7e878000	Deferred        ole32
PE	7e9a0000-7e9a3000	Deferred        shcore
PE	7e9d0000-7e9d8000	Deferred        shlwapi
PE	7ea40000-7f313000	Deferred        shell32
PE	7f410000-7f4f8000	Export          user32
PE	7f610000-7f614000	Deferred        advapi32
PE	7f690000-7f697000	Deferred        gdi32
PE	7ffd0000-7ffd4000	Deferred        version
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\home\MyHomeDir\Downloads\MIDIVisualizer-windows-32bits\MIDIVisualizer.exe
	00000009    0 <==
0000000e services.exe
	00000032    0
	0000002f    0
	0000002a    0
	00000023    0
	00000010    0
	0000000f    0
00000013 explorer.exe
	00000026    0
	00000022    0
	0000001e    0
	00000014    0
0000001c winedevice.exe
	00000027    0
	00000025    0
	00000024    0
	0000001d    0
0000001f GoogleUpdate.exe
	00000039    0
	00000038    0
	00000036    0
	00000034    0
	00000020    0
00000028 plugplay.exe
	0000002c    0
	0000002b    0
	00000029    0
0000002d winedevice.exe
	0000003a    0
	00000031    0
	00000030    0
	0000002e    0
System information:
    Wine build: wine-4.0.2 (Ubuntu 4.0.2-1)
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 5.3.0-23-generic

Thanks again for this great software.

**Comment by kosua20** [comment]
Hello, thank you for reporting this issue. The stack seems to point to an issue with OpenGL. I don't know which OpenGL version/functionalities is Wine providing exactly, though.
MIDIVisualizer >= v4.0 is requiring the same version as v3.2 so it is a bit surprising. It could also be related to the target system/libraries when compiling for Windows. I'm not very familiar with Wine expectations and support regarding this, sorry...

**Comment by ekuiter** [comment]
I have compiled a version for Linux here which you could try: https://github.com/ekuiter/MIDIVisualizer/releases/tag/v5.0

**Comment by glitterball** [comment]
> I have compiled a version for Linux here which you could try: https://github.com/ekuiter/MIDIVisualizer/releases/tag/v5.0

Works great under Kubuntu 19.10 - Thank You!
