### ISSUE TITLE
Can't hear audio

### ISSUE THREAD

**Issue by lennon12** [kosua20/MIDIVisualizer#4]
Audio not playing however everything else works fine

**Comment by lennon12** [comment]
Only mentioned that it has no audio support on the blog post

**Comment by kosua20** [comment]
Thanks, I've added a clarification to the readme.
Being able to playback the MIDI track audio would be great, but I won't have time to add it in the near future, sorry...

**Comment by lennon12** [comment]
A MIDI visualizer is pretty useless without the audio to go with it. Hope you'll add this in the future, then it'll be a good Synthesia clone!
