### ISSUE TITLE
Missing glew link on linux, segfault on launch

### ISSUE THREAD

**Issue by StickAndBindleGames** [kosua20/MIDIVisualizer#40]
Hi,
When building on Manjaro (5.4.2-1), I needed to add a CMake link to GLEW. I fail when building normally with the error:

```
/usr/bin/ld: CMakeFiles/MIDIVisualizer.dir/src/libs/imgui/imgui_impl_opengl3.cpp.o: in function `ImGui_ImplOpenGL3_SetupRenderState(ImDrawData*, int, int, unsigned int)':
imgui_impl_opengl3.cpp:(.text+0x36): undefined reference to `__glewBlendEquation'
```

This is followed by a bunch of undefined glew references. I do have glew 2.1.0-1 installed, locally.
I added the following to CMakeLists.txt in order to link glew, which does let me successfully build:

```
find_package(GLEW REQUIRED)
if (GLEW_FOUND)
    include_directories(${GLEW_INCLUDE_DIRS})
    link_libraries(${GLEW_LIBRARIES})
endif()
```

However, once built, when launching MIDIVisualizer, the program shuts down after loading the midi file.
If using sandboxing (Firejail), I get a segfault after loading the MIDI file. Though, even running un-sandboxed, it still shuts down after loading the midi file, though no error is thrown to output.

```
[INFO]: 3 tracks (Use tempo (1)).
[INFO]: 1024 units per quarter note .
[INFO]: Reading track 0.
[INFO]: Track  (length: 149, instrument: , tempo: 545544, major, measure duration: 2.18218).
[INFO]: Reading track 1.
[INFO]: Track Acoustic Grand Piano (length: 24323, instrument: , tempo: 500000, major, measure duration: 2).
[INFO]: Reading track 2.
[INFO]: Track Acoustic Grand Piano (length: 24190, instrument: , tempo: 500000, major, measure duration: 2).
[INFO]: 0 notes extracted and sorted.
[INFO]: 2707 notes extracted and sorted.
[INFO]: 2726 notes extracted and sorted.
[INFO]: Final track duration 942.95 sec.
Segmentation fault (core dumped)
```

(that's sandboxed output above. If un-sandboxed it's the same, minus the segfault).

I tested multiple midi files, and it seems unrelated to any specific file, though I am happy to upload/link one if needed for reproducing.

Judging by the location of the crash in code, I'd guess I still probably have some issue with opengl versioning/glew (it seems to crash right before creating the opengl buffers, shaders, etc in MIDIScene, but I haven't debugged from source to pinpoint it.)

Anyhow, if it seems like a platform/distro issue, don't feel obliged to dig too deep on my behalf, just figured I'd forward my edge-case. If there's log somewhere, or a debug/verbose flag I can set to get more output let me know and I'll update my findings. Thanks!

**Comment by kosua20** [comment]
Hello, the issue with GLEW is very weird. MIDIVisualizer is using gl3w to load OpenGL function endpoints, which is an alternative to GLEW. So GLEW should not be require.
My guess is ImGui (used for GUI) is detecting GLEW in the system header locations instead of finding gl3w. I've pushed a fix to force ImGui to use the gl3w header.

I'm not sure if this is going to fix the crash you observed afterwards, but this should at least allow you to compile without importing GLEW.

**Comment by StickAndBindleGames** [comment]
Hi,
That actually resolved both issues and I can compile/run without trouble.
Thanks for the quick follow through, it's much appreciated!

**Comment by StickAndBindleGames** [comment]
Hi, that resolved both the compile and runtime issues.
I appreciate the help with that, it's a fantastic asset!
Kind regards,
Tyran

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kosua20** [comment]
I'm glad this fixed the issue, always happy to help!
