### ISSUE TITLE
When I input the midi,the performance is wrong.

### ISSUE THREAD

**Issue by w86102711** [kosua20/MIDIVisualizer#42]
If  whole music is the same tempo,it will no problem.
But when you change the speed like Ritenente and Accelearando , the performance is wrong.

**Comment by w86102711** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/59832953/74102728-41801980-4b81-11ea-88b3-b1ae32fe15aa.gif)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/59832953/74102783-c9feba00-4b81-11ea-8582-a016ce06f665.gif)

**Comment by kosua20** [comment]
Hello, thank you for using MIDIVisualizer, and for reporting this issue. Could you send me a MIDI file where this occurs, so that I can reproduce the issue and try  to fix it? Thank you!

**Comment by w86102711** [comment]
[beastars-pf-solo .zip](https://github.com/kosua20/MIDIVisualizer/files/4299187/beastars-pf-solo.zip)



> Hello, thank you for using MIDIVisualizer, and for reporting this issue. Could you send me a MIDI file where this occurs, so that I can reproduce the issue and try to fix it? Thank you!

**Comment by ekuiter** [comment]
Can confirm this issue, minimum example attached (a simple tempo change suffices).

![grafik](https://user-images.githubusercontent.com/4258713/77238093-da1ca700-6bcd-11ea-8e6e-0c71f665dd0e.png)


![grafik](https://user-images.githubusercontent.com/4258713/77238063-ad688f80-6bcd-11ea-9210-5192ed9217f8.png)


[example.zip](https://github.com/kosua20/MIDIVisualizer/files/4364394/example.zip)

**Comment by ekuiter** [comment]
In [my fork](https://github.com/ekuiter/MIDIVisualizer/), I fixed this issue by using [libmidi](https://github.com/linthesia/linthesia/tree/master/src/libmidi) from Linthesia (which is based on an old Synthesia version).
This way, we can handle tempo changes correctly. (Sadly, libmidi still assumes time signature 4/4, so horizontal lines are wrong. This is another issue though.)

![grafik](https://user-images.githubusercontent.com/4258713/77322752-7e106a80-6d14-11ea-8449-2a0b26d407f4.png)

**Comment by kosua20** [comment]
Hello, I'm very happy to say that I've finally had a bit of time to allocate to MIDIVisualizer, and the timing issues are now fixed (hopefully for good this time)! I've checked MIDIVisualizer on the file you and ekuiter have shared, thank you for your help once again!

The latest v5.1 version has now been [released](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.1) with these fixes.
