### ISSUE TITLE
Help win10 bug!

### ISSUE THREAD

**Issue by MaxThrower** [kosua20/MIDIVisualizer#43]
Hi! I really want try your program.  But when I open .mid file, it's freeze and don't work. Help!! It's work on 3.4 version. But in 4.1 not working!

**Comment by kosua20** [comment]
Hello, thank you for reporting this issue. Have you observed this will all MIDI files or only some (in which case could you send me one of the MIDI files so that I can try and replicate the issue)?
Are you running on Windows, macOS, something else? Thank you!

**Comment by MaxThrower** [comment]
My OS is Windows. Yeah, I try launch some midi files

**Comment by kosua20** [comment]
Do you happen to know what GPU is in your computer. Im planning on improving the support for more MIDI file sub-formats in the future, this might help.

**Comment by kosua20** [comment]
Hello again! The latest v5.1 version that was [just released](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.1) comes with many fixes to MIDI loading and parsing, so you might want to test again with this version.
