### ISSUE TITLE
Display pedal actions and improve keyboard looking

### ISSUE THREAD

**Issue by azuwis** [kosua20/MIDIVisualizer#44]
It will be great if MIDIVisualizer can display pedal actions and improve keyboard looking.

For reference, here is a piano tutorial I created by combining MIDIVisualizer and other software, the pedal at the bottom right corner and the keyboard are from other software.

![test](https://user-images.githubusercontent.com/9315/76482111-335a3d00-644e-11ea-8f79-2f08d5fce715.gif)

Thanks for MIDIVisualizer, it really help creating piano tutorial.

**Comment by kosua20** [comment]
Hello and thank you for your feedback on MIDIVisualizer! The latest 5.2 version can now be downloaded from the [release page](https://github.com/kosua20/MIDIVisualizer/releases/latest). It adds options to adjust the size of the keyboard and display pedal events with a few options.
