### ISSUE TITLE
Different color hands

### ISSUE THREAD

**Issue by BlankNametag** [kosua20/MIDIVisualizer#46]
Hi! I just stumbled upon your visualizer and I love it!

If I may ask about anything more, could it be possible to have a way to decide either or not the visualizer plays the midi sounds or not? Also, would it be possible to have a feature that makes the two hands played different colors? If these were a thing, you program would, in my opinion, be just about perfect!

**Comment by BlankNametag** [comment]
Also, fullscreen is such a small difference but such a good one if that is possible as well.

**Comment by ekuiter** [comment]
Regarding hand separation: I have added support for this in my fork (https://github.com/ekuiter/MIDIVisualizer). It should work if your MIDI file separates both hands into different tracks.

**Comment by kosua20** [comment]
Hello, for now I've added fullscreen as an option in the settings panel. For hands and tracks support, I'm planning on working on it in the near future. Thank you!

**Comment by bahamas10** [comment]
Tossing in my vote: I'd love to see left and right hand separation in the mainline!

**Comment by kosua20** [comment]
Hello again! The latest 5.2 version now supports per-channel or per-track colors for notes and effects. You can also split notes into two sets based on a manually defined "separating key" if it's more convenient. 
It can be downloaded from the [release page](https://github.com/kosua20/MIDIVisualizer/releases/latest).
