### ISSUE TITLE
Open GL 3.1 is available, yet getting Open GL error on launch

### ISSUE THREAD

**Issue by Ultimum227** [kosua20/MIDIVisualizer#47]
Hello! I'm looking forward to using this software but I've run into a bit of an issue. I was hoping to get this working on my laptop but unfortunately I'm getting that open GL error some other users have had. I ran a GPU viewer to make sure I had Open GL 3, and turns out I've got Open GL 3.1 on my card.

OpenGL 3.1 (129 ext) - Intel(R) HD Graphics 3000

Is 3.3 required to run this software? Let me know as soon as possible! Thanks!

**Comment by ekuiter** [comment]
Yes, OpenGL 3.3 is the minimum version required. I guess this is because the shaders use instanced arrays, which were introduced in OpenGL 3.3.
So, this will probably not run on your device, sorry :/

**Comment by kosua20** [comment]
Hello,
thank you for your answer @ekuiter ! Indeed a lot of GLSL functionalities used in the project were made available in OpenGL 3.3 (explicit locations,...).
From what I can read about your GPU [on this page](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen6), the latest version supported on Windows is indeed 3.1, so updating the drivers wouldn't change anything I'm afraid.
Sorry about that...
