### ISSUE TITLE
Improve rendering

### ISSUE THREAD

**Issue by Moonie68** [kosua20/MIDIVisualizer#48]
Hello. I am SO HAPPY that there is a way to do a synthesia style recording. I have a problem, though. When I render I get 5,000 images and have to figure out how to convert them to a video without loosing the quality. I don't know if it is possible, but could you allow a 'render as video' feature? Thank you!

**Comment by kaisubr** [comment]
@Moonie68 For now, using ffmpeg should do the trick.

```
ffmpeg -r 60 -f image2 -s 1280x600 -i output_%04d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p video.mp4
```

If you have the mp3, you can create a Synthesia style playback by adding the audio afterwards:
```
ffmpeg -i video.mp4 -i audio.mp3 -codec copy -shortest playback.mp4
```

I agree that automatic video export would be useful, though.

**Comment by csillag** [comment]
@Moonie68 I am also using FFMPEG for assmebling the video.

The command I use is:

```
ffmpeg -r 50 -f image2 -i output_%04d.png -vcodec libx264 -crf 0 -preset veryslow out.mp4
```

This setting does _lossless_ conversion; therefore it will take it's time. However the resulting file will have perfect quality - a great input for any post-processing you may want to do. (I am using 50 FPS, please adjust command as necessary.)

**Comment by MysticPiano** [comment]
How Can execute this script? Please be more elaborate as i am new to programming

**Comment by kosua20** [comment]
Hello, thank you for your suggestion, and a huge thank to @kaisubr and @csillag for their help answering your question.
The latest version of MIDIVisualizer (v5.0, available [from the Releases section](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.0)) now supports direct video export. The formats are limited but should be supported by most video editing software.
