### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by meshula** [kosua20/MIDIVisualizer#49]
Hi there, I really love the look of your visualizer!

I don't have a visualizer for my LabMidi project, which is under a 2 clause BSD license. https://github.com/meshula/LabMidi  

Since you haven't listed a license, I was wondering if it would be okay with you if I forked your code to form the basis of a demo for my project?

**Comment by kosua20** [comment]
Hello! Thank you for your interest in MIDIVisualizer. I don't have a lot of time to invest in the project right now but I'm always happy to see people finding it useful.

I've picked the MIT license, compatible with BSD 2 if I recall correctly.
There are already existing forks but I hadn't clarified the licensing, so now it's done. Thank you!

**Comment by meshula** [comment]
Awesome, thank you very much!
