### ISSUE TITLE
Support for using different BG images for every frame

### ISSUE THREAD

**Issue by csillag** [kosua20/MIDIVisualizer#52]
I would like to create visualizations with animated backgrounds.

The end result is something like this:

https://www.youtube.com/watch?v=WIqP2BWB628

For a general introduction to the problem, see #51. As I have stated there, the easiest way to achieve the desired result would be the save the alpha channel into the generated PNG files. This issue describes an alternate approach.

In theory, when doing the off-line rendering to PNG files, MIDIVisualizer could take a different bg image for each frame.

I could extract the frames from the animated background video into files in a directory, and give that directory to MIDIVisualizer. Then for each frame, MIDIVisualizer could read `input000n.png`, do the magic, and save it to `output000n.png`.

When compiling those saved images to a video again, I could get my video, with MIDIVisualizer's visualization plus the animated bg.

What do you think?

Thank you.

**Comment by kosua20** [comment]
I'm closing this one due to the solution regarding #51, but thank you for this alternative suggestion!
