### ISSUE TITLE
Add an option to specify resolution of the frame.

### ISSUE THREAD

**Issue by alanfraneo** [kosua20/MIDIVisualizer#54]
By default the frame size is 1280x600 and it takes the resolution of the window. However it is not easy to resize the utlity to an exact usable resolution like 1920x1080, If there was an option to do that it would be great.

**Comment by kosua20** [comment]
Hello, thank you for your feedback! In the recent [v5.0](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.0) I've added an option for specifying the export size when generating images/videos. I'll make sure to add a similar option for the window itself in the next release, I'll keep you up to date.

**Comment by kosua20** [comment]
The latest [v5.1 version](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.1) now allows for setting the window size both in the interface and on the command line, I hope this helps.
