### ISSUE TITLE
Lag while screen recording

### ISSUE THREAD

**Issue by MysticPiano** [kosua20/MIDIVisualizer#55]
Describe the issue
I am having Laggy screen recordings. Is there anything i can do to reduce the lag. Please see the video. The top part is midi visualizer.
https://www.youtube.com/watch?v=cOMgiUHPTZc
Hardware info:
- OS: Win 10 64 - bit
- Midi Visualizer version 4.1 for Windows 64 bits.
- GPU model (Intel HD Graphics 4600)
-8GB RAM
-i3 4000 m processor

**Comment by kosua20** [comment]
Hello,
depending on your GPU and the options of your screen recorder, it's completely possible that performance suffer. You can either lower the quality in MIDIVisualizer or adjust your recording/encoding options to see if this helps.
I'm planning on working on a direct video export that would help avoid these issues.

**Comment by MysticPiano** [comment]
Yes, The direct export will help a lot.

**Comment by MysticPiano** [comment]
Sorry

**Comment by kosua20** [comment]
I've just realized I forgot to give an update here as the issue was already closed. The latest v5.1 release supports direct video recording, you can download it from the [release page](https://github.com/kosua20/MIDIVisualizer/releases/).
