### ISSUE TITLE
Build fails with v5.0 and ffmpeg enabled

### ISSUE THREAD

**Issue by funnyflowerpot** [kosua20/MIDIVisualizer#56]
Hello! First, thank you a lot for creating this pretty and helpful piece of software!

Now down to business. When I try to build the 5.0 release, I get the following error message, when `make` attempts to link the binary. I am using a mostly up-to-date 64bit Gentoo Linux on a 5.4.28 kernel, with PulseAudio, without Systemd, with a GeForce GT 540M.

```
[...]
[100%] Linking CXX executable MIDIVisualizer
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/MIDIVisualizer.dir/src/helpers/Recorder.cpp.o: in function `Recorder::initVideo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Recorder::Format)':
Recorder.cpp:(.text+0x1874): undefined reference to `sws_getContext'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/MIDIVisualizer.dir/src/helpers/Recorder.cpp.o: in function `Recorder::endVideo()':
Recorder.cpp:(.text+0x1d26): undefined reference to `sws_freeContext'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/MIDIVisualizer.dir/src/helpers/Recorder.cpp.o: in function `Recorder::addFrameToVideo(unsigned char*)':
Recorder.cpp:(.text+0x1dd3): undefined reference to `sws_scale'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/MIDIVisualizer.dir/src/helpers/Recorder.cpp.o: in function `Recorder::record(std::shared_ptr<Framebuffer> const&)':
Recorder.cpp:(.text+0x2a47): undefined reference to `sws_freeContext'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MIDIVisualizer.dir/build.make:513: MIDIVisualizer] Error 1
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/MIDIVisualizer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Steps to reproduce (for me):

```
git clone https://github.com/kosua20/MIDIVisualizer
mkdir MIDIVisualizer/build
cd MIDIVisualizer/build
cmake ..
make
```

I can workaround this issue, when I comment the following line in `CMakeLists.txt`.

```
find_package(FFMPEG)
```

Then linking succeeds and I can run the binary. The application seems to work, except that there is no sound. I also get no sound output, when I try to run the binary provided for Ubuntu that comes with this release. To be honest, there might be a chance I messed with my system configuration at some point over the years, but I remember testing MIDIVisualizer some weeks ago and getting sound then.

Quick internet research [suggested](https://stackoverflow.com/questions/27519462/undefined-reference-error-can-not-create-shared-library) that the order in which the libraries are specified (`-llib1 -lib2 ... -libn`) can cause this issue. However, I am not sure what and where I should change the `Makefile`s produced by `cmake` to test something. Please let me know, if more information is needed or I can assist with testing!

**Comment by kosua20** [comment]
Hello! Thank your for your interest in MIDIVisualizer! I think there are two distinct issues in your message, I'll try to provide suggestions for both below.
 
* Linking issue: there was a missing component requirement in the file `libs/FindFFMPEG.cmake`, as a consequence `sw_scale` was not enabled.  I've fixed this a few hours ago: https://github.com/kosua20/MIDIVisualizer/commit/837edb938ae9cee18f7e5d88109ed35a1058dc30. If you had pulled the repo before that commit, it might be worth retrying with the current HEAD. Make sure to clean the cmake cache and re-configuring and generating the project. If you still encounter the issue afterwards, we can try to look at the output makefiles to see if there are any link ordering issue.

* Missing sound: I'm sorry to say that MIDIVisualizer has never been able to play sound...😅 For now it's only a visualization tool, but this is a "nice to have" feature that is on my to-do list. Maybe you tried another similar application recently (Linthesia for instance), that had sound support?

I hope this will help, please let me know if you encounter any additional issue!

**Comment by funnyflowerpot** [comment]
Hi and thanks for the fast reply! You're right those are two issues!

> Linking issue

Indeed, I pulled before that commit and I could just compile right away!

> Missing sound

Haha, oh dear, that explains why I'm not getting sound. :facepalm: :laughing: Now that you're bringing it up, I might actually have shoved my laptop over to the music keyboard at that time some weeks (months?) ago. Blame my foggy memory, but that would explain the music I remember.

Thanks again, both issues are solved!
