### ISSUE TITLE
vcruntime140_1.dll missing

### ISSUE THREAD

**Issue by FreddieM007** [kosua20/MIDIVisualizer#57]
I tried running the latest version 5.0 but it complains about a missing vcruntime140_1.dll.

**Comment by kosua20** [comment]
Hello! Sorry to hear that ; this is a Windows component (part of the *Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019*) that is often updated, you could try installing the latest version from the Microsoft support website: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads (`vc_redistx64`).
Let me know if it helps.

**Comment by FreddieM007** [comment]
Great, that worked! Perhaps you could add that link to the install instructions. I searched for the .dll name directly but it pointed to Microsoft websites with old, outdated versions that did not install.
Now I am going to play with your tool - thanks!

**Comment by kosua20** [comment]
Great! I'll add this to a new Troubleshooting section in the Readme. Thanks!
