### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by hari-shreyas** [kosua20/MIDIVisualizer#58]
I recently installed MIDIVisualizer. I imported a MIDI File but as I started playing it, the piano roll was going on but there was no sound output. Also. I would like to change the number of keys to only 5 octaves. How do I do that? I have a MIDI Keyboard and would like to have the roll for those notes only. Thanks

**Comment by kosua20** [comment]
Hello and thank you for your feedback! Right now MIDIVisualizer doesn't support sound playback, it is only a visualisation tool. I can't promise anything on sound support for now, sorry about that...

For the keyboard I'm planning to provide additional options in one of the coming updates, if you have suggestions I would be happy to hear them.

**Comment by hari-shreyas** [comment]
Alrighty! Thanks a lot. Really like the app :D 
Is there any way to change the colour of the roll for left hand and the right hand instead of both being the same colour?

**Comment by kosua20** [comment]
I'm currently working on supporting per-channel colors. I don't think MIDI is keeping track of the hands, but if you have a different channel for each hand it will do the trick (once I've added this :) ).

**Comment by hari-shreyas** [comment]
Hmmm alright. Maybe you could try adding this: We select a key on the and the program will show a different color for the notes played after the key will be displayed in a different color. It will not be that helpful when you are switching hands but it will be good. And anyway, in most of the songs, the bass is played with the left and treble with the right and there is rarely a switch of hands. 

Anyway. Love your app. I have tried Piano from above and synthesis but this on is the best by far! amazing work :)

**Comment by kosua20** [comment]
Hello again! The latest 5.2 version now supports per-channel or per-track colors for notes and effects. You can also split notes into two sets based on a manually defined "separating key" if it's more convenient, thank you for this suggestion. 
It can be downloaded from the [release page](https://github.com/kosua20/MIDIVisualizer/releases/latest).

**Comment by hari-shreyas** [comment]
OMG that is amazing!!! Thank you soo much :D You are the best!
