### ISSUE TITLE
Sabre Just above Piano (1 PX gap)

### ISSUE THREAD

**Issue by MysticPiano** [kosua20/MIDIVisualizer#59]
Hi Kosua20,

I have come back, not for a problem but a feature.

It is a sabre like animation on top of the Piano. Can you add this to the next version. And when will version 6 be available? Please see the two pictures below for an example (see my cursor).

![image](https://user-images.githubusercontent.com/68113615/89375179-c1d79f80-d70a-11ea-9406-9037238e806a.png)

![image](https://user-images.githubusercontent.com/68113615/89375315-0a8f5880-d70b-11ea-9252-a66abb38f52b.png)

For @kosua20 

Thanks and Regards 

Mystic Piano

**Comment by kosua20** [comment]
Hello, and thank you for your suggestion! I won't necessarily have a lot of time in the coming months to work on MIDIVisualizer, but I've been able to add a first take on this wavy effect in the latest 5.2 version.
It can be downloaded from the [release page](https://github.com/kosua20/MIDIVisualizer/releases/latest).

**Comment by MysticPiano** [comment]
Hi Kosua,

How can i do this

**Comment by MysticPiano** [comment]
Oh sorry Kosua. Just realised, I hadnt installed the latest version

**Comment by MysticPiano** [comment]
Thanks for releasing ver 5.2. I would also like to suggest another feature of putting in midi info like in the screenshots below
![image](https://user-images.githubusercontent.com/68113615/89726917-c15a4400-da3d-11ea-870f-763360bbd2a9.png)
![image](https://user-images.githubusercontent.com/68113615/89726925-d46d1400-da3d-11ea-9fab-0407d48c5af0.png)
