### ISSUE TITLE
Performance problem on Mojave

### ISSUE THREAD

**Issue by turboman1** [kosua20/MIDIVisualizer#6]
I recently upgraded to Mojave from High Sierra.   When I run the make process the new executable is very laggy.  It was using 5% CPU  before,  now it is at 40% cpu usage and it brings my CPU to 80 degrees temperature.    Do you know if there is any way to fix this?  Thanks.

**Comment by kosua20** [comment]
I've started to investigate this in the past few weeks. Apple deprecated OpenGL in macOS Mojave, and it seems they really meant it. Do you use any other OpenGL-reliant application, and have you observed a similar issue?
On my side, on a test partition, I'm observing a 30% drop in graphics performance for non-trivial OpenGL applications, and a higher CPU cost. The effect is even stronger if the application is recompiled using Mojave SDK.
There are a few suboptimal things in MIDIVisualizer that I can try to fix, but I'm afraid we won't get back to the High Sierra performance level. For instance, V-sync is always off when using OpenGL on Mojave, and there are some discrepancies between the observed framerate and the one computed in the code.
I will update this issue once I have more details.

**Comment by kosua20** [comment]
Hello again,
I've updated the GLFW binaries in the repo with the latest version with an additional PR applied, containing a fix for the framerate on Mojave.
This solves the "no Vsync" issue and should help with the performances, even if the CPU use seems to remain higher than in previous OS versions.
Also, note that as soon as the framerate drop below 60fps, it will become very laggy all of a sudden. I think the Apple OpenGL driver has some trouble with this situation.

**Comment by kosua20** [comment]
I've also added various "performance modes" depending on the hardware of the machine. You can select them in the first dropdown in the UI.
There will still be some lag, those seem to be on Apple's OpenGL driver side sadly. I'll reopen if there is any update on this side.
