### ISSUE TITLE
Export Issue

### ISSUE THREAD

**Issue by MysticPiano** [kosua20/MIDIVisualizer#60]
Hi Kosua20,

So i was just exporting yesterday when the videos were choppy, distorted and pausing. Please tell me the problem that I am facing.  I exported thrice, and all of the videos were bad

This is the detailed Report

First export - IN the console, there was an error by swscaler saying dimensions not set. Video was in 2 halves of the screen and the bottom half was frozen on a single frame.

Second export - No errors. Last 300 frames frozen

Third export - No errors. All frames pausing and then moving at 2x speed

 Thanks and regards

Mystic Piano

**Comment by kosua20** [comment]
Hello, I'm sorry to here that. I' assuming it's happening on the latest v5.2 version. I might need a few extra info to help me pinpoint the exact issue:
- what is your operating system?
- which settings have you used for the export (format, resolution, framerate, bitrate,...)?
- if you just play the track in the main interface, does it play ok?

If you think that sending me the buggy videos or the MIDI track could be useful, you can do so at the email adress on my profile (https://github.com/kosua20).
Thanks for reporting the swscaler message, this will be helpful!

**Comment by MysticPiano** [comment]
My OS is Windows 10 Ver 2004
Export settings - 1920 x 1080p
                            Mpeg 4
                             40 mb/s
Yes, the midi is displayed well in the main interface.
Will send the videos too

**Comment by MysticPiano** [comment]
HI kosua,
I cant share the files as they are too large to be shared through mail. Can we have a video call maybe.....

**Comment by MysticPiano** [comment]
HI Kosua,

What should i do about this issue

In both versions, the export is glitching and there are some errors. What should i do. This is urgent

**Comment by MysticPiano** [comment]
@kosua20  Please help

**Comment by kosua20** [comment]
Hello! While I understand that this is a problem, please keep in mind that MIDIVisualizer is a free project I maintain by myself, on my free time 🙂 While I've had some time to allocate to it in July, adding many features and fixing bugs, I now have other professional and personal projects that require my attention. 

That being clarified, for now I haven't been able to reproduce the issue on multiple computers. You can upload the MIDI file and videos here: https://www.dropbox.com/request/xdJ2NmcrAyxbKyXFokQa  Hopefully this will help me pinpoint the problem a bit better.

As a temporary alternative, you could try exporting to PNG and then merge all frames into a video, using software such as VirtualDub, ShotCut, or Premiere. If you are comfortable with the ffmpeg command lin, you could also use it for this.

I also have a few extra questions, if you have the time:

* Have you tried running an older version ([5.1](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.1) or [5.0](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.0)) and if yes, was the issue still present?
* Have you tried exporting in MPEG2, and was the issue still present?

Thanks!

**Comment by MysticPiano** [comment]
@kosua20 Hi,
I have sent you the files on dropbox.
Anyway, so I downloaded ver 5.0 and the export is like really slow.
But lets hope it works.

![image](https://user-images.githubusercontent.com/68113615/90645198-4bcb5080-e253-11ea-9b71-18302ba7edef.png)
Also Why do i keep getting this error and then it changes my resolution?

**Comment by MysticPiano** [comment]
@kosua20 I will try mpeg 2

**Comment by MysticPiano** [comment]
@kosua20 I tried Mpeg 2 but that didnt work too well

**Comment by MysticPiano** [comment]
@kosua20 please reply

**Comment by kosua20** [comment]
Alright. In Shotcut:
* create a new project, pick the resolution and framerate you want (HD 1080p 60fps for instance)
* Open the first PNG of the exported track, it will appear in the "Source" panel
* In the "Properties" tab, check "Image sequence". This will automatically load other images from the directory. You will see that the duration of the "image" will be updated and if you play it in the source panel it will go through all images.
* Create a video track in the timeline
* Add the source to the timeline (the "+" button in the timeline tool bar).

It will then behave like a regular video clip, you can use it directly and add titles etc, or you can export the timeline as a video, and use this in another project. Note that the playback of image sequences can be a bit slow sometimes.
I hope this helps.

Thank you for the videos, the file and the extra log details! I don't know when I will have time to look at this, but this will be incredibly helpful.

**Comment by MysticPiano** [comment]
Thanks. I will try the frame export. Hope you fix this issue soon.

**Comment by MysticPiano** [comment]
I will ask you about the status of the issue every week though. Hope you are fine with that

**Comment by MysticPiano** [comment]
@kosua20 Thanks for changing up some stuff, I don't know, but the swscaler error has come less often when exporting in 30 FPS.
60FPS , sometimes throws out the error 

There is a new error that comes up, it is something like unexpected frame size while recording
![image](https://user-images.githubusercontent.com/68113615/100410853-ebd81780-3095-11eb-907f-280b2630b55a.png)
.

Check the console picture. 

Also, may I know the reasons of this error?
Is there any way I can export without any ERROR?

**Comment by kosua20** [comment]
Hello, thank you for providing these additional details. A quick question: are you by any chance minimizing the MIDIVisualizer windows once the export is started? or exporting while MIDIVisualizer is in complete fullscreen?

**Comment by MysticPiano** [comment]
Yes, I did minimize the window several times.

**Comment by kosua20** [comment]
OK I've found a bug with minimization/maximization during an export, that would either cause the message above or produce a garbled video, on Windows only (which is not my day-to-day OS so it went under the radar). 
[Version 5.3(1)](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.3(1)) introduces a fix for this that I've tested on Windows. Let me know if this helps.

**Comment by MysticPiano** [comment]
@kosua20 Yes, I tried minimizing 35 times during export, nothing happened. I will just close this when my export finishes and there is no swscaler error

**Comment by MysticPiano** [comment]
@kosua20 The Export in https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.3(1) Came out perfectly, 60fps, 1080p.

Just had a last question, If I can, How can I increase export speed?

**Comment by kosua20** [comment]
For the export speed there is not a lot you can do if you want to stay at 60fps 1080p, I'm afraid :/ 
I will try to push a few optimizations in future releases, but it really depends on the hardware you have.

**Comment by MysticPiano** [comment]
@kosua20 Two questions,

1) What is new in v6.0 related to export?

2) I have a friend, who has an amazing pc, MacOS but 32 - bit. Is there any way he can run the release v6.0 on 32 - bit?

**Comment by kosua20** [comment]
Hello,
v6.0 added a debug mode that can displays extra messages while exporting, in case of future export bugs. 
There is also a tweak that might speed up export. To give a brief overview, export was limited at processing 60 frames per second, (same processing speed as during rendering), while now if the computer is powerful enough it can process more frames per second. But it will depends on the GPU power, the CPU and the export resolution.
For running on Windows 32bits, everything has to be recompiled for a 32bits target, including external libraries (FFMPEG). I'll add it to the list of improvements for the future.

**Comment by kosua20** [comment]
This is fixed, closing now.
