### ISSUE TITLE
width and location of black keys

### ISSUE THREAD

**Issue by vaclavmuller** [kosua20/MIDIVisualizer#62]
Could you adjust the width and location of black keys to be more natural?

Original screenshot
![orig](https://user-images.githubusercontent.com/23431375/90333237-76ec4080-dfc4-11ea-80fc-3f7fa093ebf7.png)

Edited
![2](https://user-images.githubusercontent.com/23431375/90333242-7ce22180-dfc4-11ea-8dd4-cdc3aebfd313.png)

**Comment by kosua20** [comment]
Hello! The width can already be adjusted by using the "Minor size" slider. It will adjust the width of both the keys and the corresponding notes.
For the horizontal offset, that's a very interesting suggestion, I'll add it to the list of keyboard improvements. 
Thank you!

**Comment by kosua20** [comment]
Hello, just to let you know that the latest [6.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) features improved placement of the minor keys, with more realistic offsets 🙂
