### ISSUE TITLE
Reverse Scroll

### ISSUE THREAD

**Issue by frink** [kosua20/MIDIVisualizer#64]
Instead of raining note, what if they note bars floated upwards when a note is pressed? That way you could pipe MIDI in live...

**Comment by MysticPiano** [comment]
@frink He might use qsynth or DryWetMIDI to incorporate the live midi sounds. He is still working on that
Reversing note direction wont be so difficult I guess. The hard part would be to incorporate the libraries to make realtime midi

**Comment by frink** [comment]
I'm just thinking this could be used in live performance if the direction were reversed.

**Comment by MysticPiano** [comment]
@frink Yes, it will be nice to have a reverse scroll. Many people have already discussed the issue (#39). @kosua20 , when will this feature be incorporated into MIDI Visualizer?

**Comment by frink** [comment]
Is this a dupe of #39 then?

**Comment by MysticPiano** [comment]
Kind Of. But you reported the reverse Scroll thingy. There its only processing it.  I dont know if he meant the reverse scroll. You dont necessarily have to delete this issue

**Comment by frink** [comment]
I'll leave it since #39 is focused on the real time MIDI aspect and this is really a precursor to that.

**Comment by kosua20** [comment]
Hello everyone, thanks for your contributions to this discussion. I think we can keep this one separate, it might be useful independently of the "live play" support, as suggested by MysticPiano.
I can't give any time estimate about new features, I'm currently finishing my thesis and soon starting a new job while moving so I won't have a lot of time to allocate to MIDIVisualizer in the coming months I fear. I'll make sure to update the issues when I start tackling them.

**Comment by frink** [comment]
I may dig into it in a month or two...

**Comment by pi-kei** [comment]
I did a fork with live mode with reversed scroll.

**Comment by frink** [comment]
Very exiting!

**Comment by pi-kei** [comment]
@frink https://www.twitch.tv/computersdontcompost/clip/ResilientSneakyBaguetteDoggo

**Comment by MysticPiano** [comment]
Wow, that's nice, But where can I select the input for the MIDI?

**Comment by frink** [comment]
Yes! That'''s it!!!

**Comment by pi-kei** [comment]
> where can I select the input for the MIDI?

It's not done yet. RtMidi17 i'm using is able to list input devices and select one. Right now it is selecting the very first by default.

**Comment by kosua20** [comment]
Hello again everyone just to let you know that [release 5.3](https://github.com/kosua20/MIDIVisualizer/releases/latest) now support reverse playback properly. This is nice by itself, and will also be helpful if I add live play support at some point in the future.

**Comment by frink** [comment]
Should we close this and open another for live play?

**Comment by kosua20** [comment]
We can close this one, and #39 is already covering live play requests.
