### ISSUE TITLE
Do I have to use download and use VScmd (vcvarsall.bat)? Any alternatives

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [kosua20/MIDIVisualizer#65]
Do I seriously have to install VScmd, seems a little overkill, any alternatives?

```
C:\Users\sebas\Downloads\MIDIVisualizer-master\MIDIVisualizer-master>cMake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.


C:\Users\sebas\Downloads\MIDIVisualizer-master\MIDIVisualizer-master>cMake CmakeLists.txt
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred! 
```

**Comment by MysticPiano** [comment]
Maybe, I dont know.You may have to download it as MIDI Visualiser does use Visual C++.  If you want to run the program directly, do it from the releases section here - https://github.com/kosua20/MIDIVisualizer/releases

**Comment by MysticPiano** [comment]
@Sebastian-Nielsen

**Comment by MysticPiano** [comment]
@Sebastian-Nielsen

**Comment by Sebastian-Nielsen** [comment]
Thank you for your respond!

I just downloaded VS studio and etc. and successfully ran `cMake CMakeLists.txt`.
But what do I do now, no .exe has appeared? 

Screenshot: https://i.gyazo.com/42dd46cf78924b321443923c4b1ee6d6.png

**Comment by kosua20** [comment]
Hello, thank you for your feedback!

If your main goal is to use MIDIVisualizer, you don't have to compile it and you can find precompiled Windows binaries on the [Release page](https://github.com/kosua20/MIDIVisualizer/releases/latest).

On the other hand, if you are planning on modifying the source code to tailor MIDIVisualizer to your needs, you will have to generate a Visual Studio solution (as you successfully managed to). You can then compile it from Visual Studio itself, or by using the following command line:

    cmake --build . --config Release

This should generate a `Release/MIDIVisualizer.exe` file which is the application.

Let me know if this helps!

**Comment by MysticPiano** [comment]
@Sebastian-Nielsen Did this Work ?

**Comment by Sebastian-Nielsen** [comment]
Yes, that worked.
