### ISSUE TITLE
Piano Light, Midi Information, Direct Import of Audio And Video and Textured Notes

### ISSUE THREAD

**Issue by MysticPiano** [kosua20/MIDIVisualizer#66]
Yes, I know too many features to suggest in one issue, But I had to.

@kosua20 Please reply about how many of these features you can incorporate in the next update.

Piano Light - Replicating Lights at the area of Note contact. 

Direct Import of Audio And Video- This is also a handy feature for reducing Video editing work

Textured Notes - Notes have a texture, 

See the videos/screenshots below

![deet](https://user-images.githubusercontent.com/68113615/93732346-77dd4700-fbee-11ea-8f46-4634e099f3c0.png)

Red Area = Textured Notes
Green Area = MIDI Info
Blue area = Lights (These are real, see the second video below)

Original Video
https://www.youtube.com/watch?v=soNf2WdZWMk

Another App (not good as it is not free)
https://www.youtube.com/watch?v=NiPJyWJgIs4
Watch the second video from 7:25

These lights are also real but this software can replicate the lights.

This is my video of using this software but in trial version

https://www.youtube.com/watch?v=jsT34BmeZVc

**Comment by kosua20** [comment]
Hello, thank you for your many suggestions!

- I like the textured note idea, it could lead to very interesting effects combined with the blur.
- For the lights right now there is a flash but extra halo effects could be added, to help recreate this kind of effects (but shadowing might be more complex to support).
- Supporting additional video editing or audio compositing is not planned , I want to keep MIDIVisualizer focused on the visualisation itself. 
- For the extra labels not all users are producing content for english viewersso I would need to think about how to support custom labels.

There is no official plan for future releases or feature support as I'm in-between things right now. I will probably have to sort out licensing for this project with my new employer anyway, to be able to keep it available and maintain it.

**Comment by kosua20** [comment]
I've added the textured note and extra flash lighting ideas to the potential features list on the project page.
I think for the video/audio editing and compositing, along with the track info, people will find more convenient and flexible solutions using additional software specialized in editing and titling for instance. I could only provide a few of their features in MIDIVisualizer and this would complexify development and maintenance.
Thanks!

**Comment by kosua20** [comment]
Hello, I've added settings to overlay textures onto the notes, with additional opacity/tiling/scrolling options. This is available in the latest  [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest).
