### ISSUE TITLE
I can't hear the midi file in the software

### ISSUE THREAD

**Issue by NothingAnimated** [kosua20/MIDIVisualizer#67]
I can't hear anything when i open the midi visualizer and i have my midi in, how do i fix it

**Comment by oskeith** [comment]
You really should read the readme first, where it says, "Note that MIDIVisualizer is currently not able to play soundtracks, only display them." Also, there's another open issue where someone asks the same thing and the developer responds saying that it's "only a viewer, so there is no sound playback or export".

**Comment by MysticPiano** [comment]
@NothingAnimated It does only visualising and not sounds. He is still working on icorporating sounds

**Comment by MysticPiano** [comment]
Please close this Issue as another issue #61 exists

**Comment by kosua20** [comment]
Yes, as pointed out for now MIDIVisualizer is only a viewer, sorry... It might support audio playback in the future, but I can't promise anything right now.

**Comment by jyle635** [comment]
Question did you made this?
