### ISSUE TITLE
New effects (like fire or smoky effect) 

### ISSUE THREAD

**Issue by Randomname007** [kosua20/MIDIVisualizer#68]
Thank you so much for this. I have been searching for something similar for the last 4 years but had no luck. Your code is amazing and it would become much better if u can add more effects like fire or smoke coming instead of particles. It would be great if we could choose between a few effects in the settings. Thanks again for this midi visualizer. Keep up the good work.

**Comment by MysticPiano** [comment]
@Randomname007 you can customize the particle effect but not anmate it
![image](https://user-images.githubusercontent.com/68113615/94267839-db9ea180-ff59-11ea-8e7a-71fb414bb877.png)
You must click on load image 
 Load up to 4 black-and-white images for the custom particle effects. You can download the example from the asset pack for custom effects in the Ver 3.0 release -
https://github.com/kosua20/MIDIVisualizer/releases/tag/v3.0

**Comment by Randomname007** [comment]
Thanks @MysticPiano. I am talking about the animation effect only. To add a wavy particles animation effect like smoke instead of scattering particles. It looks really beautiful as in tbe screenshot. 
![Screenshot_20200926_094501](https://user-images.githubusercontent.com/71880654/94329973-50ff8600-ffdd-11ea-8b9d-6a4e281abd8b.jpg)

**Comment by MysticPiano** [comment]
Well, thats not available on MIDI Visualizer now. @kosua20 could help you

**Comment by aimorris** [comment]
That effect on the notes looks like Perlin noise. I can contribute this, I'll try later today.

**Comment by Loudic85** [comment]
> Merci @MysticPiano. Je ne parle que de l’effet animation. Pour ajouter un effet d’animation de particules ondulées comme la fumée au lieu de disperser les particules. Il semble vraiment beau comme dans la capture d’écran tbe.
> ![Screenshot_20200926_094501](https://user-images.githubusercontent.com/71880654/94329973-50ff8600-ffdd-11ea-8b9d-6a4e281abd8b.jpg)

Hello hox to get effect smoke for my software ? Thanks.

**Comment by sreich** [comment]
@aimorris did you ever get a chance to look into this? I agree it would be very cool

**Comment by kosua20** [comment]
I'm resurrecting this thread to let you know that I've finally added some additional turbulence noise to the particles and to the wave effect, in the latest [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest). In the future I might also add other suggestions (particle speed based on the note velocity, extra noise,...)
