### ISSUE TITLE
playing hands

### ISSUE THREAD

**Issue by vaclavmuller** [kosua20/MIDIVisualizer#69]
Just for inspiration.
https://www.youtube.com/watch?v=ta_2G0KfYh4

**Comment by kosua20** [comment]
Hello and thank you for this feedback! That's a good point, I got used to Imgui panels being small on HiDPI screens but it's not comfortable for all users, I'll see what I can do.

**Comment by kosua20** [comment]
Thank you for the suggestion ! That would be quite funny to see even if this would probably require quite a lot of work. You need good hand models with skinning, handle multiple cases of hand and fingers placement, etc. I will add it to the list of potential future features on the project page and close this issue 🙂 
Thank you once again!
