### ISSUE TITLE
particles don't work

### ISSUE THREAD

**Issue by tfdawg** [kosua20/MIDIVisualizer#7]
![image](https://user-images.githubusercontent.com/36385539/50543756-20cf4d00-0b95-11e9-84cb-b11d02341661.png)

**Comment by kosua20** [comment]
Hello, thanks for reporting this issue!
To help me pinpoint it, could you give me a few additional details: the version of macOS it's running on, and ideally the GPU brand/model?
I have a few hypothetical "quick fixes" ideas:

- try to reload the MIDI file
- try to slightly resize the window

Let me know if any of those changes anything.

Thank you!

**Comment by tfdawg** [comment]
I tried reloading the MIDI and resizing the window which both failed to fix the particles. My Macbook air  2011 is running on high sierra and has a Intel HD Graphics 3000 384MB.

**Comment by JenZ2** [comment]
I'm having the same issue here, latest version, tested on W7 Virtual Machine (since I couldnt figure how to build this for Debian (gtk errors))
Tried reloading midi and resizing (which is slow and buggy btw)
GPU: EVGA GTX 1070 

Cool project anyway, I really like it.


> Hello, thanks for reporting this issue!
> To help me pinpoint it, could you give me a few additional details: the version of macOS it's running on, and ideally the GPU brand/model?
> I have a few hypothetical "quick fixes" ideas:
> 
>     * try to reload the MIDI file
> 
>     * try to slightly resize the window
> 
> 
> Let me know if any of those changes anything.
> 
> Thank you!

**Comment by kosua20** [comment]
Thank you for this additional report, this will help me pinpoint the issue!
The next release (3.4) will fix a bug (#17) related to the particle textures that could explain the observed artifacts. I've also tweaked the size of the default particle texture just in case I was hitting some weird OpenGL limitation. I'll keep you up to date with the release.

For the gtk errors, you might want to look at the build flags for the NativeFileDialog library (https://github.com/mlabbe/nativefiledialog).

**Comment by kosua20** [comment]
I've just release MIDIVisualizer 3.4 which contains the aforementioned fixes for the particles (https://github.com/kosua20/MIDIVisualizer/releases). If you could tell me if the bug you observed is still present, that would be super helpful, thank you!
