### ISSUE TITLE
Can't set different colors to notes and minors - they always the same. 

### ISSUE THREAD

**Issue by intmainreturn00** [kosua20/MIDIVisualizer#71]
Thanks for the app and sources 🙌

**Describe the issue**
Can't set different colors to notes and minors - they always the same. 
![image](https://user-images.githubusercontent.com/1473995/97815200-7eef7e80-1c9d-11eb-89f7-b22fcc541782.png)

**Hardware info:**
- OS: macOS] - last build binary

**Comment by kosua20** [comment]
Hello and thank you for your feedback! 
You have to uncheck "Sync effect colors" to be able to adjust major and minor colors separately. I know it's not super clear and that there is no granularity (flashes and particles are also synchronized using the same check). Hopefully I'll find a clearer way of exposing this option in the future (or at least default it to unchecked). 
Let me know if this helps !
