### ISSUE TITLE
Disable Esc key to close

### ISSUE THREAD

**Issue by aimorris** [kosua20/MIDIVisualizer#75]
Disable the escape key to close the entire application (especially without warning/asking). I have made the mistake many times already trying to close a popup window with the escape key (for example, when choosing colours) and it's closed the entire application. At least a warning or asking if you really want to close first would be nice. I can try and contribute to add this in if this is something you'd like.

**Comment by MysticPiano** [comment]
@aimorris Yes, That would be nice to add a warning stating 

You are about to close the current program window.

Well, I usually am the one who fixes issues but am not in charge of program development.

@kosua20 is the Developer and only he can reply back for contributions.

I do like the feature though. It will be helpful especially when you hit esc while rendering.

**Comment by kosua20** [comment]
Hello and thank you for your feedback, I've added this in [release 5.3](https://github.com/kosua20/MIDIVisualizer/releases/latest)!
