### ISSUE TITLE
Scaling of window

### ISSUE THREAD

**Issue by aimorris** [kosua20/MIDIVisualizer#76]
Scaling of the settings window. On HiDPI displays, it is currently very small.

**Comment by kosua20** [comment]
Hello and thank you for this feedback! That's a good point, I got used to Imgui panels being small on HiDPI screens but it's not comfortable for all users, I'll see what I can do.

**Comment by kosua20** [comment]
In the latest [release 5.3](https://github.com/kosua20/MIDIVisualizer/releases/latest) I've added an option for this in the "Display" menu. You can also specify it from the command line using the `--gui-size` argument.
In the future I would like to be able to detect it automatically, but I know that different OSes are handling window resolution on HiDPI very differently.
