### ISSUE TITLE
Add units to menu options which are not self-explanatory

### ISSUE THREAD

**Issue by ahkneipp** [kosua20/MIDIVisualizer#81]
The "preroll" feature in particular could be either seconds or measures.  Menu options which could be any of multiple units should have them labelled to avoid user confusion.

**Comment by kosua20** [comment]
Hello, that's a good point, thank you for your feedback! I've started to add extra labels in [version 6.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) to clarify which units or range some values are using (timings, scalings, opacities...). Some remain quite arbitrary (based on internal parameters), but I'll see what I can do for these.
