### ISSUE TITLE
JACK MIDI input?

### ISSUE THREAD

**Issue by mxmilkiib** [kosua20/MIDIVisualizer#83]
It would be neat to be able to pipe [JACK](http://jackaudio.org/) [MIDI](https://github.com/jackaudio/jackaudio.github.com/wiki#midi) into MIDIVisualizer.

**Comment by kosua20** [comment]
Hello, that's a very good suggestion that should be quite easy to add now as rtmidi (used internally to listen to other MIDI devices) also support creating virtual devices. I'll keep you up to date!

**Comment by kosua20** [comment]
The latest [6.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) now allows MIDIVisualizer to act as a virtual MIDI device and receive events from other devices and apps. There is a dedicated button in the live play session panel ; I've tested it with VMPK, let me know if you encounter any issue.

**Comment by mxmilkiib** [comment]
Awesome, thanks!

Here I'm using a2jmidid to connect an LV2 midi generator running under JACK to the ALSA virtual device for MIDIVisualizer;
![image](https://user-images.githubusercontent.com/108225/101866067-d374fc00-3b6f-11eb-8555-80bc45398afd.png)

Native JACK support would still be nice if you were up for it though.

**Comment by kosua20** [comment]
For this I would need to document more on JACK and the different types of devices. I'm closing this issue for now but will make a note of it in the potential features list on the [project page](https://github.com/kosua20/MIDIVisualizer/projects/1) !
