### ISSUE TITLE
Improve Pedal Design

### ISSUE THREAD

**Issue by MysticPiano** [kosua20/MIDIVisualizer#87]
The Current pedal design is not that great and is not quite realistic, I was thinking of adding a texture and changing the shape of the pedals. I can contribute this.

**Comment by sreich** [comment]
@MysticPiano I agree. do you have a graphic to offer for this? Or suggestion or ideas to throw out there?

**Comment by kosua20** [comment]
Hello, the latest [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) now allows you to customize the look and color of each pedal by loading custom images, in a new dedicated configuration panel.
