### ISSUE TITLE
Horizontal Mode

### ISSUE THREAD

**Issue by JacobADaniels** [kosua20/MIDIVisualizer#89]
Hey there! Thanks for your work on this great tool.  

I was thinking that it'd be great to have a horizontal mode, more like the piano roll MIDI editors so many of us are used to using in our DAWs.  I'm trying to do it currently by cropping and rotating the video, but it's just not coming out as nicely as if there was a native horizontal mode.

**Comment by MysticPiano** [comment]
@JacobADaniels Welcome to GitHub and MIDI Visualizer issues.
First of all, Congratulations on opening your first issue. 
MIDI Visualizer, is not a DAW, and cannot export in a horizontal mode **currently**. If you could please let me know, for what kind of videos, you make/want to make, I could suggest different methods/help you make a video (as said above).

**Comment by JacobADaniels** [comment]
Hey there, 
So far, I've only got one video.  Here it is: https://www.youtube.com/watch?v=XFpwGd9cJJ0

I was trying to rotate it so that the notes were scrolling from right to left, but I ended up leaving it vertical.  Since it's a vocal piece, I switched off the keyboard layer.  I did have a different issue, actually, and I think it's something to do with the tempo map?  Over the course of the song, notes kind of came out of phase with the measures?  Like, the notes would start a little before the each score line, and the error just added up over the song.  I'm happy to share my midi file with you if it's any help.

**Comment by MysticPiano** [comment]
@JacobADaniels 

Well, that was a really good video, nevertheless. But if you still want to rotate, you might have to do it in a video editor and will distort your video, I suggest you keep it like this, but if you really want to rotate you need to edit the video. Here's your video I edited into horizontal mode. Note that I had to remove your text to make it look good. Also I suggest you add a bit more reverb 

https://user-images.githubusercontent.com/68113615/103434499-23535a00-4c28-11eb-9bc3-85433fb434ca.mp4

And for the second issue, Please send me the MIDI File as a zip here or to the email in my profile.

Hope that helped!

**Comment by kosua20** [comment]
Hello @JacobADaniels  and thank you for this suggestion! Horizontal scrolling is now available in the latest [6.3 release](https://github.com/kosua20/MIDIVisualizer/releases/latest)
For the other issue I would indeed be interested in getting the MIDI file that exhibits the issue if it's still present in the latest release.
