### ISSUE TITLE
No Glow Left Behind (With Blur On)

### ISSUE THREAD

**Issue by MadLad0913** [kosua20/MIDIVisualizer#9]
Hello! I think it would be great if the particles and notes had their own individual blur like this:
**https://imgur.com/gallery/pBKu3rE**
At the moment, the particles in the visualizer (when blur is turned on) leaves behind a glow, that can get messy when a lot of notes are on screen. Is there any way to remove this glow from being "left behind" like in the image?

**Comment by kosua20** [comment]
Hello! I can easily expose the attenuation speed of the blur, this should already help reduce the trailing glow and get something closer to a "fixed blur". I'll update this issue once this is released.

**Comment by kosua20** [comment]
Hello, the latest 3.2 release now support setting the attenuation factor for the blur in the interface!
