### ISSUE TITLE
Note off events stop notes even if they are on a different channel

### ISSUE THREAD

**Issue by 4321ba** [kosua20/MIDIVisualizer#90]
Just a small bug, it isn't a problem if it isn't fixed.
**Describe the issue**
MIDI Note off events stop notes even if they are on a different channel.

**Hardware info:**
- OS: Ubuntu
- MIDIVisualizer version v6.2
- GPU model Nvidia GeForce 750
- RAM 8GB

![Screenshot_20210107_171230](https://user-images.githubusercontent.com/39439556/103915720-da117780-510b-11eb-8f57-8c7a7c1756c9.png)
All the notes here should be the same length if they are not cut by another note. If they are, I made the MIDI so that the note off events happen before the next note on event (on the same channel). However, you can see that the 2 channels interfere (F# in the middle), my midi uses the same track, but different channels. First the green note off stops the blue note from being long. Then the next blue's note off stops the green, and that green's note off stops the next blue before it's supposed to end.

I think it is alright if the note on a given channel stops before it should, when a new note on happens on a different channel (meaning I don't think the program needs to draw notes on eachother). I don't actually know the midi specification that well but I don't think note off events from different channels should interfere this way (like a harp note shouldn't stop because a bass note off was called), I might be wrong though.

Also, MIDI file, it's like 20 seconds after the beginning:
[145_Everpresence_Eldritch_Outlook.zip](https://github.com/kosua20/MIDIVisualizer/files/5782817/145_Everpresence_Eldritch_Outlook.zip)

**Comment by kosua20** [comment]
Hello, thank you for this detailed report and for providing a test file! I've been able to pinpoint the bug and fix it. As you mentioned, when two notes from different channels overlap, one is going to hide the other, but at least now the durations should be correct. This is available in the latest [6.3 release](https://github.com/kosua20/MIDIVisualizer/releases/latest)

**Comment by 4321ba** [comment]
Thanks! And I see you solved that too e.g. when a long note plays on B and after that a short one plays too which turns quickly off, the old long one will remain on.
![Screenshot_20210316_140256](https://user-images.githubusercontent.com/39439556/111313176-5078ab80-8660-11eb-877e-7c0db650268d.png)
Everything seems to work fine, so I'll close this.
