### ISSUE TITLE
Ability to Change Postroll/End Buffer in Exports

### ISSUE THREAD

**Issue by duckboycool** [kosua20/MIDIVisualizer#91]
For exporting out a video either through the command line or the GUI, I wasn't able to find a way to change how long after the end of the MIDI that the export keeps going for, which the window calls buffer. It seemed like it was stuck at the 10s default.

If I didn't just miss it, and this isn't something you're able to do, I think it would be a helpful addition to have. It would be similar to how you can change the preroll time from the default 1s.

**Comment by kosua20** [comment]
Hello, thank you for this suggestion, it is now available in the latest [6.3 release](https://github.com/kosua20/MIDIVisualizer/releases/latest): a new post-roll option is offered in the export panel.
