### ISSUE TITLE
Segmentation fault in Linux Mint 20.1

### ISSUE THREAD

**Issue by defensem3ch** [kosua20/MIDIVisualizer#93]
**Describe the issue**
Running `./MIDIVisualizer` with the attached config and MIDI file caused a crash when exporting to mp4. Console output:

```
❯ ./MIDIVisualizer
[INFO]: 5 tracks (Tempo track (1)).
[INFO]: 480 units per quarter note .
[INFO]: Reading track 0.
[INFO]: Track  (length: 25, instrument: , major).
[INFO]: Reading track 1.
[INFO]: Track 1 (length: 6445, instrument: , major).
[INFO]: Reading track 2.
[INFO]: Track 2 (length: 6881, instrument: , major).
[INFO]: Reading track 3.
[INFO]: Track 3 (length: 8970, instrument: , major).
[INFO]: Reading track 4.
[INFO]: Track 4 (length: 10025, instrument: , major).
[INFO]: Final track duration 216.94 sec.
[EXPORT]: Processing frame 2503/6839.[1]    17469 segmentation fault (core dumped)  ./MIDIVisualizer
```

**Hardware info:**
- OS: Linux Mint 20.1 x64
- MIDIVisualizer version: 6.2
- GPU model: nVIDIA GeForce GTX 650 Ti
- 8 GB RAM
[midiconfig.ini.txt](https://github.com/kosua20/MIDIVisualizer/files/6047141/midiconfig.ini.txt)
[tracks(4).mid.zip](https://github.com/kosua20/MIDIVisualizer/files/6047145/tracks.4.mid.zip)

**Comment by defensem3ch** [comment]
My apologies, it looks like this is a duplicate of #82 - I will build from source in the meantime!

**Comment by defensem3ch** [comment]
Update: this happens even when building from the latest commit

**Comment by kosua20** [comment]
Hello, and thank you for reporting this issue! I've managed to reproduce the issue using the files you provided, I'll keep you up to date once this is solved.

**Comment by kosua20** [comment]
The latest [6.3 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) should fix this issue. Some notes were outside the standard MIDI range and were not properly handled by MIDIVisualizer.
