### ISSUE TITLE
Add transparency support to video export, too

### ISSUE THREAD

**Issue by csillag** [kosua20/MIDIVisualizer#94]
It would be great to get alpha transparency to work for video output too.

Currently it works great for PNG export, but my main use case is video, and as far as I can tell, with the current version (6.2), the alpha channel is lost when generating an MP4 file.

These links might be relevant:
 * https://www.digitalrebellion.com/blog/posts/list_of_video_formats_supporting_alpha_channels
 *  https://www.reddit.com/r/ffmpeg/comments/a06oxh/best_format_to_compress_transparent_video/

Thanks.

**Comment by csillag** [comment]
I can confirm the using the series of generated PNG files as input for FFMPEG works as intended... just slow and cumbersome.
(Direct video export would be much faster.)

**Comment by csillag** [comment]
When implementing video export, my preference would be speed and image quality. I don't care about output file size; it can even be uncompressed, because this is only an intermediary start; it's the input of another round of ffmpeg processing, and I will apply proper compression then and there.

(Hence, doing video compression during the midi visualization phase is just a waste of time for me.)

**Comment by csillag** [comment]
@kosua20 here is a recent example, generated using the transparent PNG export method:

https://vimeo.com/520439875/189232a7be

**Comment by kosua20** [comment]
Hello, thank you for this detailed issue! I'm planning on adding support for the ProRes format as FFMPEG supports it well, would this be convenient for your process?

**Comment by csillag** [comment]
If it works with FFMPEG, then it's good enough for me, too. (I will use it as input for FFMPEG.)

My considerations are
 - speed
 - image quality.

Within ProRes, I would go for 4444 XQ, 1920 × 1080, 50p, 16 bit alpha....
.... and set parameters for best speed, as described [here](https://ffmpeg.org/ffmpeg-codecs.html#toc-Speed-considerations).

Thanks.

**Comment by kosua20** [comment]
Hello again, thank you once again for these details! From what I understood from the FFMPEG documentation, the fast ProRes codec is picked by default and the "best parameters" suggested in the list are for the fallback, slower codec. I've still used the suggested settings in MIDIVisualizer, in case this fallback happens on some platforms.
The latest [6.3 release](https://github.com/kosua20/MIDIVisualizer/releases/latest) now support ProRes export.

**Comment by csillag** [comment]
Thank you for the new feature! I have made some testing with the performance, with a 70 seconds long track.
 * Exporting to PNG: 327 seconds
 * Exporting directly to video: 169 seconds

.. so basically, it's twice as fast now, which is obviously great.

Here is my latest export, using transparent background in ProRes format:

https://vimeo.com/426953775/edf6e71efa 

So as far as I am concerned, this issue can be closed now.

**Comment by sxjeru** [comment]
Excuse me, although I successfully exported the mov file with alpha channel, it doesn't seem to be supported by Adobe premiere, i.e. the background is still black. And no alpha channel was recognized.

`MIDIVisualizer 6.5`
