### ISSUE TITLE
Wave animation is not showing

### ISSUE THREAD

**Issue by oliverz27** [kosua20/MIDIVisualizer#98]
Thank you for your interest in MIDIVisualizer, and thank you for reporting issues!
Don't forget to check the [troubleshooting section](https://github.com/kosua20/MIDIVisualizer/blob/master/README.md#troubleshooting), there might be information related to your issue. Don't forget to also check if other people have reported a similar issue on the [dedicated page](https://github.com/kosua20/MIDIVisualizer/issues). Finally, make sure that you are using the latest version listed on the [releases page](https://github.com/kosua20/MIDIVisualizer/releases).

Please help me pinpoint (and hopefully fix) the issue more quickly by filling in the information below.
If you are not sure about some of the details asked below, don't worry, you can leave them blank.
**Describe the issue**
**Wave animation is not showing on the new release 6.3**

**Hardware info:**
- OS: **Windows 7 64 Bit**
- MIDIVisualizer version: **6.3**
- GPU model: **Intel HD Graphics 520**
- RAM available: **8GB**

Please don't forget that MIDIVisualizer is a personal project that I maintain on my free time, free to use and open source :)

**Comment by kosua20** [comment]
Thank you for reporting this issue! When running MIDIVisualizer, do you get any messages in the logging window? This could help me pinpoint the issue more accurately. I will also try to replicate the issue on my side once I get a Windows machine at hand.
